double * _internal_t_tangent_vectors = nullptr;
out_gpu___CG_p_nh__CG_metrics__m_ddqz_z_full_e = p_nh->metrics->ddqz_z_full_e;
// out_gpu___CG_p_nh__CG_diag__m_mass_fl_e = p_nh->diag->mass_fl_e; // Comment out because lhs is not in the SDFG arrays
out___CG_p_patch__m_nblks_c = p_patch->nblks_c;
out_gpu___CG_p_nh__CG_diag__m_rho_ic = p_nh->diag->rho_ic;
out_gpu___CG_p_int__m_c_lin_e = p_int->c_lin_e;
out_gpu___CG_p_int__m_nudgecoeff_e = p_int->nudgecoeff_e;
out___CG_p_nh__CG_metrics__m_pg_exdist = p_nh->metrics->pg_exdist;
// out_gpu___CG_p_nh__CG_metrics__m_deepatmo_divh_mc = p_nh->metrics->deepatmo_divh_mc; // Comment out because lhs is not in the SDFG arrays
out_gpu___CG_p_patch__CG_verts__m_cell_blk = p_patch->verts->cell_blk;
out_gpu___CG_p_nh__CG_diag__m_ddt_vn_phd = p_nh->diag->ddt_vn_phd;
out_gpu___CG_p_nh__CG_diag__m_ddt_vn_ray = p_nh->diag->ddt_vn_ray;
out_gpu___CG_p_patch__CG_edges__m_vertex_blk = p_patch->edges->vertex_blk;
out_gpu___CG_p_patch__CG_verts__m_cell_idx = p_patch->verts->cell_idx;
out___CG_global_data__m_timer_intp = global_data->timer_intp;
out___CG_global_data__m_nproma = global_data->nproma;
// out_gpu___CG_p_int__m_geofac_grg = p_int->geofac_grg; // Comment out because lhs is not in the SDFG arrays
out___CG_p_nh__CG_metrics__m_pg_listdim = p_nh->metrics->pg_listdim;
// out_gpu___CG_p_nh__CG_diag__m_w_int = p_nh->diag->w_int; // Comment out because lhs is not in the SDFG arrays
out_gpu___CG_p_nh__CG_metrics__m_rayleigh_vn = p_nh->metrics->rayleigh_vn;
// out_gpu___CG_p_nh__CG_metrics__m_coeff_gradp = p_nh->metrics->coeff_gradp; // Comment out because lhs is not in the SDFG arrays
out_gpu___CG_p_patch__CG_edges__m_f_e = p_patch->edges->f_e;
out_gpu___CG_p_patch__CG_cells__m_neighbor_blk = p_patch->cells->neighbor_blk;
out___CG_global_data__m_rayleigh_type = global_data->rayleigh_type;
// out_gpu___CG_p_nh__CG_metrics__m_exner_exfac = p_nh->metrics->exner_exfac; // Comment out because lhs is not in the SDFG arrays
// out_gpu___CG_p_nh__CG_diag__m_grf_tend_mflx = p_nh->diag->grf_tend_mflx; // Comment out because lhs is not in the SDFG arrays
out___CG_p_patch__m_nshift = p_patch->nshift;
out___CG_p_nh__CG_diag__m_ddt_vn_ray_is_associated = p_nh->diag->ddt_vn_ray_is_associated;
// out_gpu___CG_p_nh__CG_diag__m_grf_tend_w = p_nh->diag->grf_tend_w; // Comment out because lhs is not in the SDFG arrays
out_gpu___CG_p_nh__CG_ref__m_vn_ref = p_nh->ref->vn_ref;
out_gpu___CG_p_nh__CG_metrics__m_wgtfac_e = p_nh->metrics->wgtfac_e;
out___CG_global_data__m_lextra_diffu = global_data->lextra_diffu;
out___CG_global_data__m_divdamp_order = global_data->divdamp_order;
out_gpu___CG_p_nh__CG_diag__m_ddt_vn_dyn = p_nh->diag->ddt_vn_dyn;
// out_gpu___CG_prep_adv__m_mass_flx_me = prep_adv->mass_flx_me; // Comment out because lhs is not in the SDFG arrays
out_gpu___CG_p_nh__CG_diag__m_vn_ie = p_nh->diag->vn_ie;
out___CG_global_data__m_divdamp_fac_o2 = global_data->divdamp_fac_o2;
out_gpu___CG_p_nh__CG_metrics__m_coeff1_dwdz = p_nh->metrics->coeff1_dwdz;
out_gpu___CG_p_int__m_rbf_vec_coeff_e = p_int->rbf_vec_coeff_e;
out_gpu___CG_p_patch__CG_cells__CG_decomp_info__m_owner_mask = p_patch->cells->decomp_info->owner_mask;
out_gpu___CG_p_nh_prog_nnew__m_rho = p_nh_prog_nnew->rho;
out___CG_global_data__m_timer_solve_nh_cellcomp = global_data->timer_solve_nh_cellcomp;
out_gpu___CG_p_int__m_cells_aw_verts = p_int->cells_aw_verts;
out___CG_p_patch__CG_edges__m_end_block = p_patch->edges->end_block;
out___CG_p_nh__CG_diag__m_ddt_vn_grf_is_associated = p_nh->diag->ddt_vn_grf_is_associated;
out___CG_global_data__m_timer_solve_nh_vnupd = global_data->timer_solve_nh_vnupd;
out_gpu___CG_p_patch__CG_cells__m_area = p_patch->cells->area;
out_gpu___CG_p_patch__CG_verts__m_edge_blk = p_patch->verts->edge_blk;
out_gpu___CG_p_patch__CG_edges__m_vertex_idx = p_patch->edges->vertex_idx;
out_gpu___CG_p_nh__CG_metrics__m_coeff2_dwdz = p_nh->metrics->coeff2_dwdz;
out___CG_p_nh__CG_metrics__m_bdy_mflx_e_dim = p_nh->metrics->bdy_mflx_e_dim;
out___CG_global_data__m_nflatlev = global_data->nflatlev;
out_gpu___CG_p_nh__CG_metrics__m_wgtfacq_e = p_nh->metrics->wgtfacq_e;
out___CG_p_nh__CG_metrics__m_bdy_mflx_e_idx = p_nh->metrics->bdy_mflx_e_idx;
out___CG_p_patch__m_nblks_v = p_patch->nblks_v;
out___CG_global_data__m_timers_level = global_data->timers_level;
// out_gpu___CG_p_nh__CG_diag__m_theta_v_ic_int = p_nh->diag->theta_v_ic_int; // Comment out because lhs is not in the SDFG arrays
out_gpu___CG_p_nh__CG_metrics__m_ddxn_z_full = p_nh->metrics->ddxn_z_full;
out___CG_p_patch__CG_edges__m_start_index = p_patch->edges->start_index;
// out_gpu___CG_p_nh__CG_diag__m_rho_incr = p_nh->diag->rho_incr; // Comment out because lhs is not in the SDFG arrays
out_gpu___CG_p_nh__CG_diag__m_ddt_vn_dmp = p_nh->diag->ddt_vn_dmp;
// out_gpu___CG_p_nh__CG_metrics__m_d2dexdz2_fac2_mc = p_nh->metrics->d2dexdz2_fac2_mc; // Comment out because lhs is not in the SDFG arrays
// out_gpu___CG_p_nh__CG_metrics__m_deepatmo_invr_ifc = p_nh->metrics->deepatmo_invr_ifc; // Comment out because lhs is not in the SDFG arrays
out_gpu___CG_p_patch__CG_edges__m_tangent_orientation = p_patch->edges->tangent_orientation;
out_gpu___CG_p_nh__CG_metrics__m_ddqz_z_half = p_nh->metrics->ddqz_z_half;
out_gpu___CG_p_nh__CG_diag__m_ddt_vn_phy = p_nh->diag->ddt_vn_phy;
out_gpu___CG_p_nh__CG_metrics__m_hmask_dd3d = p_nh->metrics->hmask_dd3d;
// out_gpu___CG_p_int__m_pos_on_tplane_e = p_int->pos_on_tplane_e; // Comment out because lhs is not in the SDFG arrays
out_gpu___CG_p_nh_prog_nnew__m_w = p_nh_prog_nnew->w;
// out_gpu___CG_p_nh__CG_diag__m_rho_ic_ubc = p_nh->diag->rho_ic_ubc; // Comment out because lhs is not in the SDFG arrays
out_gpu___CG_p_nh_prog_nnow__m_rho = p_nh_prog_nnow->rho;
out_gpu___CG_p_nh_prog_nnow__m_vn = p_nh_prog_nnow->vn;
out___CG_p_patch__CG_cells__m_end_block = p_patch->cells->end_block;
out___CG_p_nh__CG_diag__m_ddt_vn_dyn_is_associated = p_nh->diag->ddt_vn_dyn_is_associated;
// out_gpu___CG_p_int__m_e_flx_avg = p_int->e_flx_avg; // Comment out because lhs is not in the SDFG arrays
// out_gpu___CG_p_nh__CG_diag__m_grf_tend_thv = p_nh->diag->grf_tend_thv; // Comment out because lhs is not in the SDFG arrays
out_gpu___CG_p_patch__CG_cells__m_edge_idx = p_patch->cells->edge_idx;
out_gpu___CG_p_nh_prog_nnew__m_vn = p_nh_prog_nnew->vn;
// out_gpu___CG_p_nh__CG_metrics__m_vertidx_gradp = p_nh->metrics->vertidx_gradp; // Comment out because lhs is not in the SDFG arrays
out_gpu___CG_p_int__m_e_bln_c_s = p_int->e_bln_c_s;
out___CG_p_patch__CG_edges__m_start_block = p_patch->edges->start_block;
// out_gpu___CG_p_nh__CG_diag__m_grf_tend_vn = p_nh->diag->grf_tend_vn; // Comment out because lhs is not in the SDFG arrays
out_gpu___CG_p_nh__CG_diag__m_ddt_vn_cor = p_nh->diag->ddt_vn_cor;
// out_gpu___CG_p_nh_prog_nnew__m_exner = p_nh_prog_nnew->exner; // Comment out because lhs is not in the SDFG arrays
// out_gpu___CG_p_nh__CG_diag__m_grf_bdy_mflx = p_nh->diag->grf_bdy_mflx; // Comment out because lhs is not in the SDFG arrays
// out_gpu___CG_p_int__m_geofac_div = p_int->geofac_div; // Comment out because lhs is not in the SDFG arrays
out_gpu___CG_p_nh__CG_diag__m_ddt_vn_cor_pc = p_nh->diag->ddt_vn_cor_pc;
out___CG_p_patch__CG_cells__m_start_blk = p_patch->cells->start_blk;
out_gpu___CG_p_patch__CG_edges__m_quad_blk = p_patch->edges->quad_blk;
// out_gpu___CG_prep_adv__m_vol_flx_ic = prep_adv->vol_flx_ic; // Comment out because lhs is not in the SDFG arrays
out___CG_global_data__m_ldeepatmo = global_data->ldeepatmo;
out___CG_global_data__m_is_iau_active = global_data->is_iau_active;
// out_gpu___CG_p_nh__CG_metrics__m_rayleigh_w = p_nh->metrics->rayleigh_w; // Comment out because lhs is not in the SDFG arrays
out___CG_p_patch__m_n_childdom = p_patch->n_childdom;
out___CG_global_data__m_l_limited_area = global_data->l_limited_area;
// out_gpu___CG_p_nh__CG_diag__m_w_ubc = p_nh->diag->w_ubc; // Comment out because lhs is not in the SDFG arrays
// out_gpu___CG_p_nh__CG_metrics__m_rho_ref_mc = p_nh->metrics->rho_ref_mc; // Comment out because lhs is not in the SDFG arrays
out___CG_p_nh__CG_metrics__m_pg_edgeidx = p_nh->metrics->pg_edgeidx;
out___CG_global_data__m_timer_solve_nh_veltend = global_data->timer_solve_nh_veltend;
out___CG_global_data__m_divdamp_fac = global_data->divdamp_fac;
out_gpu___CG_p_nh__CG_metrics__m_vwind_expl_wgt = p_nh->metrics->vwind_expl_wgt;
out_gpu___CG_p_patch__CG_cells__m_neighbor_idx = p_patch->cells->neighbor_idx;
out_gpu___CG_p_nh__CG_diag__m_vt = p_nh->diag->vt;
// out_gpu___CG_p_nh__CG_metrics__m_exner_ref_mc = p_nh->metrics->exner_ref_mc; // Comment out because lhs is not in the SDFG arrays
out___CG_p_patch__m_nlev = p_patch->nlev;
out_gpu___CG_p_nh__CG_diag__m_ddt_w_adv_pc = p_nh->diag->ddt_w_adv_pc;
// out_gpu___CG_p_nh_prog_nnow__m_exner = p_nh_prog_nnow->exner; // Comment out because lhs is not in the SDFG arrays
// out_gpu___CG_p_nh__CG_metrics__m_deepatmo_gradh_ifc = p_nh->metrics->deepatmo_gradh_ifc; // Comment out because lhs is not in the SDFG arrays
// out_gpu___CG_p_patch__CG_edges__m_refin_ctrl = p_patch->edges->refin_ctrl; // Comment out because lhs is not in the SDFG arrays
// out_gpu___CG_p_nh__CG_diag__m_grf_tend_rho = p_nh->diag->grf_tend_rho; // Comment out because lhs is not in the SDFG arrays
out_gpu___CG_p_nh__CG_diag__m_ddt_vn_apc_pc = p_nh->diag->ddt_vn_apc_pc;
out_gpu___CG_p_nh__CG_metrics__m_coeff_gradekin = p_nh->metrics->coeff_gradekin;
// out_gpu___CG_p_nh__CG_diag__m_mass_fl_e_sv = p_nh->diag->mass_fl_e_sv; // Comment out because lhs is not in the SDFG arrays
// out_gpu___CG_p_nh__CG_metrics__m_theta_ref_ic = p_nh->metrics->theta_ref_ic; // Comment out because lhs is not in the SDFG arrays
out___CG_p_patch__CG_cells__m_end_index = p_patch->cells->end_index;
out___CG_p_patch__CG_edges__m_end_index = p_patch->edges->end_index;
out___CG_global_data__m_i_am_accel_node = global_data->i_am_accel_node;
out_gpu___CG_p_nh__CG_metrics__m_d_exner_dz_ref_ic = p_nh->metrics->d_exner_dz_ref_ic;
out_gpu___CG_p_nh_prog_nnew__m_theta_v = p_nh_prog_nnew->theta_v;
// out_gpu___CG_p_nh__CG_diag__m_mflx_ic_ubc = p_nh->diag->mflx_ic_ubc; // Comment out because lhs is not in the SDFG arrays
// out_gpu___CG_prep_adv__m_mass_flx_ic = prep_adv->mass_flx_ic; // Comment out because lhs is not in the SDFG arrays
out___CG_p_nh__CG_diag__m_ddt_vn_dmp_is_associated = p_nh->diag->ddt_vn_dmp_is_associated;
// out_gpu___CG_p_nh__CG_diag__m_ddt_exner_phy = p_nh->diag->ddt_exner_phy; // Comment out because lhs is not in the SDFG arrays
// out_gpu___CG_p_nh__CG_metrics__m_zdiff_gradp = p_nh->metrics->zdiff_gradp; // Comment out because lhs is not in the SDFG arrays
// out_gpu___CG_p_nh__CG_metrics__m_vwind_impl_wgt = p_nh->metrics->vwind_impl_wgt; // Comment out because lhs is not in the SDFG arrays
// out_gpu___CG_p_nh__CG_metrics__m_inv_ddqz_z_full = p_nh->metrics->inv_ddqz_z_full; // Comment out because lhs is not in the SDFG arrays
out___CG_p_patch__m_nlevp1 = p_patch->nlevp1;
out___CG_global_data__m_divdamp_type = global_data->divdamp_type;
// out_gpu___CG_p_nh__CG_diag__m_theta_v_ic_ubc = p_nh->diag->theta_v_ic_ubc; // Comment out because lhs is not in the SDFG arrays
out_gpu___CG_p_int__m_geofac_n2s = p_int->geofac_n2s;
// out_gpu___CG_p_nh__CG_diag__m_vn_ie_int = p_nh->diag->vn_ie_int; // Comment out because lhs is not in the SDFG arrays
// out_gpu___CG_p_nh__CG_metrics__m_wgtfacq_c = p_nh->metrics->wgtfacq_c; // Comment out because lhs is not in the SDFG arrays
out_gpu___CG_p_patch__CG_edges__m_quad_idx = p_patch->edges->quad_idx;
out___CG_p_nh__CG_diag__m_max_vcfl_dyn = p_nh->diag->max_vcfl_dyn;
out_gpu___CG_p_nh__CG_metrics__m_theta_ref_mc = p_nh->metrics->theta_ref_mc;
out_gpu___CG_p_patch__CG_edges__m_inv_primal_edge_length = p_patch->edges->inv_primal_edge_length;
out_gpu___CG_p_patch__CG_edges__m_area_edge = p_patch->edges->area_edge;
out_gpu___CG_p_nh__CG_diag__m_ddt_vn_iau = p_nh->diag->ddt_vn_iau;
out_gpu___CG_p_patch__CG_edges__m_cell_idx = p_patch->edges->cell_idx;
// out_gpu___CG_p_nh__CG_metrics__m_deepatmo_invr_mc = p_nh->metrics->deepatmo_invr_mc; // Comment out because lhs is not in the SDFG arrays
// out_gpu___CG_p_patch__CG_edges__m_ft_e = p_patch->edges->ft_e; // Comment out because lhs is not in the SDFG arrays
out___CG_global_data__m_nrdmax = global_data->nrdmax;
out___CG_p_nh__CG_diag__m_ddt_vn_adv_is_associated = p_nh->diag->ddt_vn_adv_is_associated;
out_gpu___CG_p_nh__CG_metrics__m_scalfac_dd3d = p_nh->metrics->scalfac_dd3d;
out___CG_p_nh__CG_metrics__m_pg_edgeblk = p_nh->metrics->pg_edgeblk;
out___CG_p_nh__CG_metrics__m_bdy_mflx_e_blk = p_nh->metrics->bdy_mflx_e_blk;
out___CG_global_data__m_lvert_nest = global_data->lvert_nest;
out_gpu___CG_p_patch__CG_edges__m_cell_blk = p_patch->edges->cell_blk;
out_gpu___CG_p_patch__CG_edges__m_inv_dual_edge_length = p_patch->edges->inv_dual_edge_length;
out_gpu___CG_p_nh__CG_diag__m_ddt_vn_adv = p_nh->diag->ddt_vn_adv;
out_gpu___CG_p_nh__CG_diag__m_vn_incr = p_nh->diag->vn_incr;
// out_gpu___CG_p_nh__CG_metrics__m_deepatmo_divzu_mc = p_nh->metrics->deepatmo_divzu_mc; // Comment out because lhs is not in the SDFG arrays
// out_gpu___CG_p_nh__CG_metrics__m_wgtfacq1_c = p_nh->metrics->wgtfacq1_c; // Comment out because lhs is not in the SDFG arrays
// out_gpu___CG_p_patch__CG_edges__CA_dual_normal_cell__CG_t_tangent_vectors__m_v2 = &(p_patch->edges->dual_normal_cell[((__f2dace_SA_dual_normal_cell_d_0_s_235_edges_p_patch_9 * __f2dace_SA_dual_normal_cell_d_1_s_236_edges_p_patch_9) * __f2dace_SA_dual_normal_cell_d_2_s_237_edges_p_patch_9)]); // Comment out because lhs is not in the SDFG arrays
out___CG_p_nh__CG_diag__m_ddt_vn_phd_is_associated = p_nh->diag->ddt_vn_phd_is_associated;
// out_gpu___CG_p_nh__CG_metrics__m_rho_ref_me = p_nh->metrics->rho_ref_me; // Comment out because lhs is not in the SDFG arrays
out_gpu___CG_p_nh__CG_diag__m_theta_v_ic = p_nh->diag->theta_v_ic;
out___CG_p_patch__CG_verts__m_end_block = p_patch->verts->end_block;
// out_gpu___CG_p_patch__CG_edges__CA_dual_normal_cell__CG_t_tangent_vectors__m_v1 = &(p_patch->edges->dual_normal_cell[0]); // Comment out because lhs is not in the SDFG arrays
// out_gpu___CG_p_patch__CG_edges__CA_primal_normal_cell__CG_t_tangent_vectors__m_v1 = &(p_patch->edges->primal_normal_cell[0]); // Comment out because lhs is not in the SDFG arrays
out_gpu___CG_p_nh__CG_diag__m_ddt_vn_pgr = p_nh->diag->ddt_vn_pgr;
// out_gpu___CG_p_nh__CG_ref__m_w_ref = p_nh->ref->w_ref; // Comment out because lhs is not in the SDFG arrays
out_gpu___CG_p_patch__CG_cells__m_edge_blk = p_patch->cells->edge_blk;
out___CG_p_nh__CG_diag__m_ddt_vn_iau_is_associated = p_nh->diag->ddt_vn_iau_is_associated;
// out_gpu___CG_p_nh__CG_diag__m_rho_ic_int = p_nh->diag->rho_ic_int; // Comment out because lhs is not in the SDFG arrays
out___CG_p_patch__CG_cells__m_end_blk = p_patch->cells->end_blk;
// out_gpu___CG_p_nh__CG_diag__m_ddt_vn_grf = p_nh->diag->ddt_vn_grf; // Comment out because lhs is not in the SDFG arrays
// out_gpu___CG_prep_adv__m_vn_traj = prep_adv->vn_traj; // Comment out because lhs is not in the SDFG arrays
// out_gpu___CG_p_nh__CG_metrics__m_theta_ref_me = p_nh->metrics->theta_ref_me; // Comment out because lhs is not in the SDFG arrays
out___CG_p_patch__CG_verts__m_end_index = p_patch->verts->end_index;
out___CG_p_nh__CG_diag__m_ddt_vn_pgr_is_associated = p_nh->diag->ddt_vn_pgr_is_associated;
// out_gpu___CG_p_patch__CG_edges__CA_primal_normal_cell__CG_t_tangent_vectors__m_v2 = &(p_patch->edges->primal_normal_cell[((__f2dace_SA_primal_normal_cell_d_0_s_232_edges_p_patch_9 * __f2dace_SA_primal_normal_cell_d_1_s_233_edges_p_patch_9) * __f2dace_SA_primal_normal_cell_d_2_s_234_edges_p_patch_9)]); // Comment out because lhs is not in the SDFG arrays
// out_gpu___CG_p_patch__CG_edges__m_fn_e = p_patch->edges->fn_e; // Comment out because lhs is not in the SDFG arrays
out___CG_p_patch__m_id = p_patch->id;
out___CG_p_nh__CG_metrics__m_pg_vertidx = p_nh->metrics->pg_vertidx;
out___CG_p_patch__CG_cells__m_start_block = p_patch->cells->start_block;
out___CG_p_nh__CG_diag__m_ddt_vn_cor_is_associated = p_nh->diag->ddt_vn_cor_is_associated;
out_gpu___CG_p_patch__CG_verts__m_edge_idx = p_patch->verts->edge_idx;
out_gpu___CG_p_int__m_geofac_rot = p_int->geofac_rot;
out___CG_p_patch__CG_verts__m_start_block = p_patch->verts->start_block;
// out_gpu___CG_p_nh__CG_metrics__m_deepatmo_gradh_mc = p_nh->metrics->deepatmo_gradh_mc; // Comment out because lhs is not in the SDFG arrays
// out_gpu___CG_p_nh__CG_diag__m_exner_incr = p_nh->diag->exner_incr; // Comment out because lhs is not in the SDFG arrays
// out_gpu___CG_p_nh_prog_nnow__m_w = p_nh_prog_nnow->w; // Comment out because lhs is not in the SDFG arrays
out_gpu___CG_p_nh_prog_nnow__m_theta_v = p_nh_prog_nnow->theta_v;
out___CG_global_data__m_iau_wgt_dyn = global_data->iau_wgt_dyn;
// out_gpu___CG_p_nh__CG_diag__m_mflx_ic_int = p_nh->diag->mflx_ic_int; // Comment out because lhs is not in the SDFG arrays
out_gpu___CG_p_nh__CG_diag__m_w_concorr_c = p_nh->diag->w_concorr_c;
out_gpu___CG_p_nh__CG_metrics__m_wgtfac_c = p_nh->metrics->wgtfac_c;
out_gpu___CG_p_int__m_geofac_grdiv = p_int->geofac_grdiv;
out___CG_global_data__m_kstart_dd3d = global_data->kstart_dd3d;
// out_gpu___CG_p_nh__CG_diag__m_exner_dyn_incr = p_nh->diag->exner_dyn_incr; // Comment out because lhs is not in the SDFG arrays
out_gpu___CG_p_nh__CG_metrics__m_ddxt_z_full = p_nh->metrics->ddxt_z_full;
out_gpu___CG_p_nh__CG_diag__m_exner_pr = p_nh->diag->exner_pr;
// out_gpu___CG_p_nh__CG_metrics__m_deepatmo_divzl_mc = p_nh->metrics->deepatmo_divzl_mc; // Comment out because lhs is not in the SDFG arrays
out___CG_p_patch__CG_verts__m_start_index = p_patch->verts->start_index;
out___CG_p_patch__CG_cells__m_start_index = p_patch->cells->start_index;
out___CG_global_data__m_itime_scheme = global_data->itime_scheme;
out___CG_p_patch__m_nblks_e = p_patch->nblks_e;
// out_gpu___CG_p_nh__CG_diag__m_vn_ie_ubc = p_nh->diag->vn_ie_ubc; // Comment out because lhs is not in the SDFG arrays
// out_gpu___CG_p_nh__CG_metrics__m_d2dexdz2_fac1_mc = p_nh->metrics->d2dexdz2_fac1_mc; // Comment out because lhs is not in the SDFG arrays