double * _internal_t_tangent_vectors = nullptr;
// out_gpu___CG_p_nh__CG_diag__m_ddt_vn_phy = p_nh->diag->ddt_vn_phy; // Comment out because lhs is not in the SDFG arrays
out_gpu___CG_p_nh__CG_metrics__m_inv_ddqz_z_full = p_nh->metrics->inv_ddqz_z_full;
// out_gpu___CG_p_nh__CG_diag__m_vn_ie_ubc = p_nh->diag->vn_ie_ubc; // Comment out because lhs is not in the SDFG arrays
out_gpu___CG_p_nh_prog_nnew__m_exner = p_nh_prog_nnew->exner;
out_gpu___CG_p_nh__CG_metrics__m_vwind_impl_wgt = p_nh->metrics->vwind_impl_wgt;
out___CG_p_nh__CG_diag__m_ddt_vn_dyn_is_associated = p_nh->diag->ddt_vn_dyn_is_associated;
out_gpu___CG_p_nh__CG_diag__m_vt = p_nh->diag->vt;
// out_gpu___CG_p_nh__CG_metrics__m_d_exner_dz_ref_ic = p_nh->metrics->d_exner_dz_ref_ic; // Comment out because lhs is not in the SDFG arrays
out___CG_global_data__m_iau_wgt_dyn = global_data->iau_wgt_dyn;
out_gpu___CG_p_nh__CG_metrics__m_exner_ref_mc = p_nh->metrics->exner_ref_mc;
// out_gpu___CG_p_patch__CG_edges__m_cell_blk = p_patch->edges->cell_blk; // Comment out because lhs is not in the SDFG arrays
out_gpu___CG_p_nh__CG_diag__m_exner_dyn_incr = p_nh->diag->exner_dyn_incr;
out___CG_p_nh__CG_metrics__m_pg_edgeblk = p_nh->metrics->pg_edgeblk;
out___CG_p_nh__CG_diag__m_ddt_vn_dmp_is_associated = p_nh->diag->ddt_vn_dmp_is_associated;
out___CG_p_patch__CG_verts__m_start_block = p_patch->verts->start_block;
out___CG_p_patch__CG_edges__m_end_index = p_patch->edges->end_index;
out___CG_p_nh__CG_diag__m_ddt_vn_ray_is_associated = p_nh->diag->ddt_vn_ray_is_associated;
// out_gpu___CG_p_nh__CG_diag__m_ddt_vn_ray = p_nh->diag->ddt_vn_ray; // Comment out because lhs is not in the SDFG arrays
out_gpu___CG_p_nh__CG_diag__m_rho_ic = p_nh->diag->rho_ic;
// out_gpu___CG_p_nh__CG_diag__m_ddt_vn_grf = p_nh->diag->ddt_vn_grf; // Comment out because lhs is not in the SDFG arrays
out___CG_global_data__m_kstart_dd3d = global_data->kstart_dd3d;
out_gpu___CG_p_patch__CG_cells__m_edge_blk = p_patch->cells->edge_blk;
out_gpu___CG_p_nh__CG_diag__m_grf_bdy_mflx = p_nh->diag->grf_bdy_mflx;
// out_gpu___CG_p_patch__CG_edges__m_area_edge = p_patch->edges->area_edge; // Comment out because lhs is not in the SDFG arrays
// out_gpu___CG_p_nh__CG_diag__m_rho_ic_ubc = p_nh->diag->rho_ic_ubc; // Comment out because lhs is not in the SDFG arrays
out___CG_p_nh__CG_diag__m_max_vcfl_dyn = p_nh->diag->max_vcfl_dyn;
// out_gpu___CG_p_nh__CG_diag__m_ddt_vn_dmp = p_nh->diag->ddt_vn_dmp; // Comment out because lhs is not in the SDFG arrays
out_gpu___CG_prep_adv__m_vn_traj = prep_adv->vn_traj;
out_gpu___CG_p_nh_prog_nnow__m_theta_v = p_nh_prog_nnow->theta_v;
out_gpu___CG_p_nh__CG_metrics__m_ddxn_z_full = p_nh->metrics->ddxn_z_full;
// out_gpu___CG_p_int__m_pos_on_tplane_e = p_int->pos_on_tplane_e; // Comment out because lhs is not in the SDFG arrays
out_gpu___CG_p_nh__CG_diag__m_mflx_ic_ubc = p_nh->diag->mflx_ic_ubc;
out___CG_p_patch__CG_edges__m_end_block = p_patch->edges->end_block;
out___CG_p_patch__CG_verts__m_end_block = p_patch->verts->end_block;
// out_gpu___CG_p_nh__CG_metrics__m_rho_ref_mc = p_nh->metrics->rho_ref_mc; // Comment out because lhs is not in the SDFG arrays
out___CG_p_nh__CG_metrics__m_bdy_mflx_e_idx = p_nh->metrics->bdy_mflx_e_idx;
// out_gpu___CG_p_patch__CG_edges__CA_primal_normal_cell__CG_t_tangent_vectors__m_v1 = &(p_patch->edges->primal_normal_cell[0]); // Comment out because lhs is not in the SDFG arrays
// out_gpu___CG_p_patch__CG_cells__CG_decomp_info__m_owner_mask = p_patch->cells->decomp_info->owner_mask; // Comment out because lhs is not in the SDFG arrays
out_gpu___CG_p_nh_prog_nnew__m_theta_v = p_nh_prog_nnew->theta_v;
out_gpu___CG_p_nh_prog_nnow__m_rho = p_nh_prog_nnow->rho;
// out_gpu___CG_p_patch__CG_edges__m_inv_primal_edge_length = p_patch->edges->inv_primal_edge_length; // Comment out because lhs is not in the SDFG arrays
// out_gpu___CG_p_patch__CG_cells__m_area = p_patch->cells->area; // Comment out because lhs is not in the SDFG arrays
out___CG_global_data__m_itime_scheme = global_data->itime_scheme;
out_gpu___CG_p_nh_prog_nnew__m_w = p_nh_prog_nnew->w;
// out_gpu___CG_p_nh_prog_nnow__m_vn = p_nh_prog_nnow->vn; // Comment out because lhs is not in the SDFG arrays
out___CG_p_patch__m_nlevp1 = p_patch->nlevp1;
out_gpu___CG_prep_adv__m_mass_flx_ic = prep_adv->mass_flx_ic;
out___CG_p_patch__m_nblks_v = p_patch->nblks_v;
out___CG_p_patch__CG_cells__m_start_block = p_patch->cells->start_block;
// out_gpu___CG_p_nh__CG_metrics__m_coeff_gradekin = p_nh->metrics->coeff_gradekin; // Comment out because lhs is not in the SDFG arrays
out_gpu___CG_p_nh__CG_metrics__m_ddqz_z_half = p_nh->metrics->ddqz_z_half;
// out_gpu___CG_p_nh__CG_metrics__m_coeff2_dwdz = p_nh->metrics->coeff2_dwdz; // Comment out because lhs is not in the SDFG arrays
// out_gpu___CG_p_patch__CG_edges__m_inv_dual_edge_length = p_patch->edges->inv_dual_edge_length; // Comment out because lhs is not in the SDFG arrays
// out_gpu___CG_p_nh__CG_metrics__m_theta_ref_mc = p_nh->metrics->theta_ref_mc; // Comment out because lhs is not in the SDFG arrays
// out_gpu___CG_p_nh__CG_metrics__m_hmask_dd3d = p_nh->metrics->hmask_dd3d; // Comment out because lhs is not in the SDFG arrays
out_gpu___CG_p_nh__CG_metrics__m_ddqz_z_full_e = p_nh->metrics->ddqz_z_full_e;
// out_gpu___CG_p_nh__CG_metrics__m_wgtfacq1_c = p_nh->metrics->wgtfacq1_c; // Comment out because lhs is not in the SDFG arrays
// out_gpu___CG_p_nh__CG_metrics__m_deepatmo_invr_mc = p_nh->metrics->deepatmo_invr_mc; // Comment out because lhs is not in the SDFG arrays
out___CG_p_patch__CG_cells__m_end_blk = p_patch->cells->end_blk;
// out_gpu___CG_p_nh__CG_metrics__m_d2dexdz2_fac2_mc = p_nh->metrics->d2dexdz2_fac2_mc; // Comment out because lhs is not in the SDFG arrays
// out_gpu___CG_p_patch__CG_edges__m_vertex_idx = p_patch->edges->vertex_idx; // Comment out because lhs is not in the SDFG arrays
out___CG_p_patch__CG_cells__m_end_index = p_patch->cells->end_index;
out___CG_p_nh__CG_diag__m_ddt_vn_adv_is_associated = p_nh->diag->ddt_vn_adv_is_associated;
// out_gpu___CG_p_nh__CG_diag__m_ddt_vn_phd = p_nh->diag->ddt_vn_phd; // Comment out because lhs is not in the SDFG arrays
// out_gpu___CG_p_nh__CG_metrics__m_zdiff_gradp = p_nh->metrics->zdiff_gradp; // Comment out because lhs is not in the SDFG arrays
out___CG_global_data__m_l_limited_area = global_data->l_limited_area;
out___CG_p_patch__CG_cells__m_start_index = p_patch->cells->start_index;
// out_gpu___CG_p_nh__CG_ref__m_vn_ref = p_nh->ref->vn_ref; // Comment out because lhs is not in the SDFG arrays
out_gpu___CG_p_int__m_geofac_div = p_int->geofac_div;
out___CG_global_data__m_grf_intmethod_e = global_data->grf_intmethod_e;
out_gpu___CG_p_nh__CG_metrics__m_wgtfacq_c = p_nh->metrics->wgtfacq_c;
// out_gpu___CG_p_nh__CG_diag__m_grf_tend_w = p_nh->diag->grf_tend_w; // Comment out because lhs is not in the SDFG arrays
// out_gpu___CG_p_patch__CG_verts__m_cell_idx = p_patch->verts->cell_idx; // Comment out because lhs is not in the SDFG arrays
out___CG_p_nh__CG_diag__m_ddt_vn_cor_is_associated = p_nh->diag->ddt_vn_cor_is_associated;
// out_gpu___CG_p_nh__CG_diag__m_vn_ie_int = p_nh->diag->vn_ie_int; // Comment out because lhs is not in the SDFG arrays
// out_gpu___CG_p_nh__CG_metrics__m_vertidx_gradp = p_nh->metrics->vertidx_gradp; // Comment out because lhs is not in the SDFG arrays
// out_gpu___CG_p_int__m_c_lin_e = p_int->c_lin_e; // Comment out because lhs is not in the SDFG arrays
// out_gpu___CG_p_int__m_geofac_grg = p_int->geofac_grg; // Comment out because lhs is not in the SDFG arrays
out___CG_p_nh__CG_diag__m_ddt_vn_phd_is_associated = p_nh->diag->ddt_vn_phd_is_associated;
out___CG_global_data__m_is_iau_active = global_data->is_iau_active;
out_gpu___CG_p_patch__CG_cells__m_edge_idx = p_patch->cells->edge_idx;
out_gpu___CG_p_nh__CG_diag__m_w_ubc = p_nh->diag->w_ubc;
out_gpu___CG_p_nh__CG_diag__m_mass_fl_e_sv = p_nh->diag->mass_fl_e_sv;
// out_gpu___CG_p_patch__CG_verts__m_edge_idx = p_patch->verts->edge_idx; // Comment out because lhs is not in the SDFG arrays
// out_gpu___CG_p_patch__CG_edges__m_f_e = p_patch->edges->f_e; // Comment out because lhs is not in the SDFG arrays
// out_gpu___CG_p_nh__CG_metrics__m_theta_ref_ic = p_nh->metrics->theta_ref_ic; // Comment out because lhs is not in the SDFG arrays
out___CG_p_nh__CG_diag__m_ddt_vn_pgr_is_associated = p_nh->diag->ddt_vn_pgr_is_associated;
out_gpu___CG_p_nh__CG_diag__m_theta_v_ic_int = p_nh->diag->theta_v_ic_int;
// out_gpu___CG_p_nh__CG_metrics__m_wgtfac_e = p_nh->metrics->wgtfac_e; // Comment out because lhs is not in the SDFG arrays
out_gpu___CG_p_nh__CG_metrics__m_deepatmo_divzu_mc = p_nh->metrics->deepatmo_divzu_mc;
out___CG_p_patch__m_n_childdom = p_patch->n_childdom;
out___CG_p_patch__CG_cells__m_start_blk = p_patch->cells->start_blk;
out_gpu___CG_p_nh_prog_nnew__m_rho = p_nh_prog_nnew->rho;
// out_gpu___CG_p_patch__CG_cells__m_neighbor_idx = p_patch->cells->neighbor_idx; // Comment out because lhs is not in the SDFG arrays
// out_gpu___CG_p_patch__CG_edges__CA_primal_normal_cell__CG_t_tangent_vectors__m_v2 = &(p_patch->edges->primal_normal_cell[((__f2dace_SA_primal_normal_cell_d_0_s_202_edges_p_patch_9 * __f2dace_SA_primal_normal_cell_d_1_s_203_edges_p_patch_9) * __f2dace_SA_primal_normal_cell_d_2_s_204_edges_p_patch_9)]); // Comment out because lhs is not in the SDFG arrays
out___CG_global_data__m_rayleigh_type = global_data->rayleigh_type;
// out_gpu___CG_p_nh__CG_metrics__m_deepatmo_invr_ifc = p_nh->metrics->deepatmo_invr_ifc; // Comment out because lhs is not in the SDFG arrays
// out_gpu___CG_p_nh__CG_diag__m_grf_tend_thv = p_nh->diag->grf_tend_thv; // Comment out because lhs is not in the SDFG arrays
out_gpu___CG_p_int__m_rbf_vec_coeff_e = p_int->rbf_vec_coeff_e;
// out_gpu___CG_p_nh__CG_metrics__m_exner_exfac = p_nh->metrics->exner_exfac; // Comment out because lhs is not in the SDFG arrays
out___CG_global_data__m_kstart_moist = global_data->kstart_moist;
// out_gpu___CG_p_patch__CG_edges__m_cell_idx = p_patch->edges->cell_idx; // Comment out because lhs is not in the SDFG arrays
// out_gpu___CG_p_patch__CG_verts__m_edge_blk = p_patch->verts->edge_blk; // Comment out because lhs is not in the SDFG arrays
// out_gpu___CG_p_nh__CG_diag__m_theta_v_ic_ubc = p_nh->diag->theta_v_ic_ubc; // Comment out because lhs is not in the SDFG arrays
// out_gpu___CG_p_nh__CG_metrics__m_rayleigh_w = p_nh->metrics->rayleigh_w; // Comment out because lhs is not in the SDFG arrays
// out_gpu___CG_p_nh__CG_diag__m_ddt_vn_dyn = p_nh->diag->ddt_vn_dyn; // Comment out because lhs is not in the SDFG arrays
// out_gpu___CG_p_int__m_cells_aw_verts = p_int->cells_aw_verts; // Comment out because lhs is not in the SDFG arrays
out_gpu___CG_p_nh_prog_nnew__m_vn = p_nh_prog_nnew->vn;
out_gpu___CG_p_patch__CG_edges__m_quad_blk = p_patch->edges->quad_blk;
out___CG_p_nh__CG_metrics__m_pg_listdim = p_nh->metrics->pg_listdim;
out___CG_p_nh__CG_diag__m_ddt_vn_iau_is_associated = p_nh->diag->ddt_vn_iau_is_associated;
out___CG_p_nh__CG_diag__m_ddt_vn_grf_is_associated = p_nh->diag->ddt_vn_grf_is_associated;
out___CG_p_nh__CG_metrics__m_pg_edgeidx = p_nh->metrics->pg_edgeidx;
// out_gpu___CG_p_patch__CG_verts__m_cell_blk = p_patch->verts->cell_blk; // Comment out because lhs is not in the SDFG arrays
// out_gpu___CG_p_nh__CG_diag__m_grf_tend_rho = p_nh->diag->grf_tend_rho; // Comment out because lhs is not in the SDFG arrays
out___CG_p_nh__CG_metrics__m_pg_vertidx = p_nh->metrics->pg_vertidx;
// out_gpu___CG_p_nh__CG_metrics__m_theta_ref_me = p_nh->metrics->theta_ref_me; // Comment out because lhs is not in the SDFG arrays
// out_gpu___CG_p_nh__CG_metrics__m_coeff_gradp = p_nh->metrics->coeff_gradp; // Comment out because lhs is not in the SDFG arrays
// out_gpu___CG_p_nh__CG_metrics__m_scalfac_dd3d = p_nh->metrics->scalfac_dd3d; // Comment out because lhs is not in the SDFG arrays
out___CG_p_patch__CG_verts__m_end_index = p_patch->verts->end_index;
// out_gpu___CG_p_int__m_geofac_n2s = p_int->geofac_n2s; // Comment out because lhs is not in the SDFG arrays
// out_gpu___CG_p_int__m_nudgecoeff_e = p_int->nudgecoeff_e; // Comment out because lhs is not in the SDFG arrays
out___CG_p_patch__CG_edges__m_start_block = p_patch->edges->start_block;
out_gpu___CG_p_nh__CG_diag__m_mflx_ic_int = p_nh->diag->mflx_ic_int;
// out_gpu___CG_p_patch__CG_edges__CA_dual_normal_cell__CG_t_tangent_vectors__m_v1 = &(p_patch->edges->dual_normal_cell[0]); // Comment out because lhs is not in the SDFG arrays
out___CG_global_data__m_ndyn_substeps_var = global_data->ndyn_substeps_var;
out_gpu___CG_p_nh__CG_diag__m_rho_incr = p_nh->diag->rho_incr;
out___CG_p_patch__m_nshift = p_patch->nshift;
// out_gpu___CG_p_patch__CG_cells__m_neighbor_blk = p_patch->cells->neighbor_blk; // Comment out because lhs is not in the SDFG arrays
out___CG_global_data__m_nflatlev = global_data->nflatlev;
out___CG_p_nh__CG_metrics__m_pg_exdist = p_nh->metrics->pg_exdist;
out_gpu___CG_p_nh__CG_diag__m_exner_incr = p_nh->diag->exner_incr;
out_gpu___CG_p_nh__CG_metrics__m_ddxt_z_full = p_nh->metrics->ddxt_z_full;
out_gpu___CG_p_nh__CG_diag__m_exner_pr = p_nh->diag->exner_pr;
out_gpu___CG_p_nh__CG_metrics__m_vwind_expl_wgt = p_nh->metrics->vwind_expl_wgt;
// out_gpu___CG_p_patch__CG_edges__m_vertex_blk = p_patch->edges->vertex_blk; // Comment out because lhs is not in the SDFG arrays
out_gpu___CG_p_nh__CG_diag__m_mass_fl_e = p_nh->diag->mass_fl_e;
// out_gpu___CG_p_nh__CG_metrics__m_d2dexdz2_fac1_mc = p_nh->metrics->d2dexdz2_fac1_mc; // Comment out because lhs is not in the SDFG arrays
out_gpu___CG_p_patch__CG_edges__m_quad_idx = p_patch->edges->quad_idx;
out___CG_p_patch__CG_verts__m_start_index = p_patch->verts->start_index;
out_gpu___CG_p_nh__CG_diag__m_rho_ic_int = p_nh->diag->rho_ic_int;
// out_gpu___CG_p_nh__CG_diag__m_vn_ie = p_nh->diag->vn_ie; // Comment out because lhs is not in the SDFG arrays
// out_gpu___CG_p_nh__CG_diag__m_grf_tend_mflx = p_nh->diag->grf_tend_mflx; // Comment out because lhs is not in the SDFG arrays
out___CG_global_data__m_nproma = global_data->nproma;
// out_gpu___CG_p_int__m_geofac_grdiv = p_int->geofac_grdiv; // Comment out because lhs is not in the SDFG arrays
// out_gpu___CG_p_nh__CG_metrics__m_coeff1_dwdz = p_nh->metrics->coeff1_dwdz; // Comment out because lhs is not in the SDFG arrays
// out_gpu___CG_p_nh__CG_metrics__m_rho_ref_me = p_nh->metrics->rho_ref_me; // Comment out because lhs is not in the SDFG arrays
// out_gpu___CG_p_patch__CG_edges__m_fn_e = p_patch->edges->fn_e; // Comment out because lhs is not in the SDFG arrays
out_gpu___CG_p_int__m_e_bln_c_s = p_int->e_bln_c_s;
out___CG_p_patch__m_nlev = p_patch->nlev;
out___CG_p_patch__CG_cells__m_end_block = p_patch->cells->end_block;
out___CG_p_nh__CG_metrics__m_bdy_mflx_e_dim = p_nh->metrics->bdy_mflx_e_dim;
out___CG_p_patch__m_nblks_e = p_patch->nblks_e;
// out_gpu___CG_p_nh__CG_metrics__m_wgtfacq_e = p_nh->metrics->wgtfacq_e; // Comment out because lhs is not in the SDFG arrays
out___CG_global_data__m_timer_solve_nh_edgecomp = global_data->timer_solve_nh_edgecomp;
out_gpu___CG_p_nh__CG_diag__m_ddt_w_adv_pc = p_nh->diag->ddt_w_adv_pc;
// out_gpu___CG_p_nh__CG_diag__m_ddt_vn_cor = p_nh->diag->ddt_vn_cor; // Comment out because lhs is not in the SDFG arrays
// out_gpu___CG_p_patch__CG_edges__m_tangent_orientation = p_patch->edges->tangent_orientation; // Comment out because lhs is not in the SDFG arrays
// out_gpu___CG_p_nh__CG_metrics__m_deepatmo_gradh_mc = p_nh->metrics->deepatmo_gradh_mc; // Comment out because lhs is not in the SDFG arrays
out___CG_global_data__m_timer_solve_nh_vimpl = global_data->timer_solve_nh_vimpl;
// out_gpu___CG_p_nh__CG_metrics__m_rayleigh_vn = p_nh->metrics->rayleigh_vn; // Comment out because lhs is not in the SDFG arrays
out___CG_global_data__m_nrdmax = global_data->nrdmax;
out_gpu___CG_p_nh_prog_nnow__m_exner = p_nh_prog_nnow->exner;
out_gpu___CG_p_nh__CG_diag__m_w_int = p_nh->diag->w_int;
out___CG_p_nh__CG_metrics__m_bdy_mflx_e_blk = p_nh->metrics->bdy_mflx_e_blk;
// out_gpu___CG_p_patch__CG_edges__m_ft_e = p_patch->edges->ft_e; // Comment out because lhs is not in the SDFG arrays
out_gpu___CG_p_nh_prog_nnow__m_w = p_nh_prog_nnow->w;
out___CG_p_patch__m_nblks_c = p_patch->nblks_c;
out_gpu___CG_p_patch__CG_edges__m_refin_ctrl = p_patch->edges->refin_ctrl;
// out_gpu___CG_p_nh__CG_diag__m_ddt_vn_pgr = p_nh->diag->ddt_vn_pgr; // Comment out because lhs is not in the SDFG arrays
out_gpu___CG_p_nh__CG_metrics__m_deepatmo_divh_mc = p_nh->metrics->deepatmo_divh_mc;
// out_gpu___CG_p_nh__CG_metrics__m_deepatmo_gradh_ifc = p_nh->metrics->deepatmo_gradh_ifc; // Comment out because lhs is not in the SDFG arrays
out___CG_p_patch__CG_edges__m_start_index = p_patch->edges->start_index;
out_gpu___CG_prep_adv__m_mass_flx_me = prep_adv->mass_flx_me;
// out_gpu___CG_p_int__m_geofac_rot = p_int->geofac_rot; // Comment out because lhs is not in the SDFG arrays
// out_gpu___CG_p_nh__CG_diag__m_ddt_vn_adv = p_nh->diag->ddt_vn_adv; // Comment out because lhs is not in the SDFG arrays
// out_gpu___CG_p_patch__CG_edges__CA_dual_normal_cell__CG_t_tangent_vectors__m_v2 = &(p_patch->edges->dual_normal_cell[((__f2dace_SA_dual_normal_cell_d_0_s_205_edges_p_patch_9 * __f2dace_SA_dual_normal_cell_d_1_s_206_edges_p_patch_9) * __f2dace_SA_dual_normal_cell_d_2_s_207_edges_p_patch_9)]); // Comment out because lhs is not in the SDFG arrays
// out_gpu___CG_p_nh__CG_diag__m_ddt_vn_cor_pc = p_nh->diag->ddt_vn_cor_pc; // Comment out because lhs is not in the SDFG arrays
out_gpu___CG_p_int__m_e_flx_avg = p_int->e_flx_avg;
out_gpu___CG_p_nh__CG_diag__m_theta_v_ic = p_nh->diag->theta_v_ic;
out___CG_global_data__m_timers_level = global_data->timers_level;
out_gpu___CG_p_nh__CG_metrics__m_deepatmo_divzl_mc = p_nh->metrics->deepatmo_divzl_mc;
// out_gpu___CG_p_nh__CG_ref__m_w_ref = p_nh->ref->w_ref; // Comment out because lhs is not in the SDFG arrays
out___CG_p_patch__m_id = p_patch->id;
out_gpu___CG_p_nh__CG_diag__m_w_concorr_c = p_nh->diag->w_concorr_c;
out_gpu___CG_prep_adv__m_vol_flx_ic = prep_adv->vol_flx_ic;
out_gpu___CG_p_nh__CG_metrics__m_wgtfac_c = p_nh->metrics->wgtfac_c;
// out_gpu___CG_p_nh__CG_diag__m_vn_incr = p_nh->diag->vn_incr; // Comment out because lhs is not in the SDFG arrays
// out_gpu___CG_p_nh__CG_diag__m_ddt_vn_apc_pc = p_nh->diag->ddt_vn_apc_pc; // Comment out because lhs is not in the SDFG arrays
// out_gpu___CG_p_nh__CG_diag__m_ddt_vn_iau = p_nh->diag->ddt_vn_iau; // Comment out because lhs is not in the SDFG arrays
out_gpu___CG_p_nh__CG_diag__m_ddt_exner_phy = p_nh->diag->ddt_exner_phy;
// out_gpu___CG_p_nh__CG_diag__m_grf_tend_vn = p_nh->diag->grf_tend_vn; // Comment out because lhs is not in the SDFG arrays