
#ifndef __DACE_CODEGEN_SOLVE_NH__
#define __DACE_CODEGEN_SOLVE_NH__

#include <dace/dace.h>


struct t_int_state {
    double* c_lin_e = {};
double* cells_aw_verts = {};
double* e_bln_c_s = {};
double* e_flx_avg = {};
double* geofac_div = {};
double* geofac_grdiv = {};
double* geofac_grg = {};
double* geofac_n2s = {};
double* geofac_rot = {};
double* nudgecoeff_e = {};
double* pos_on_tplane_e = {};
double* rbf_vec_coeff_e = {};
};


struct t_tangent_vectors {
    double v1 = {};
double v2 = {};
};


struct t_grid_domain_decomp_info {
    int* owner_mask = {};
};


struct t_grid_cells {
    int __f2dace_SA_area_d_0_s_64 = {};
int __f2dace_SA_area_d_1_s_65 = {};
int __f2dace_SOA_area_d_0_s_64 = {};
int __f2dace_SOA_area_d_1_s_65 = {};
double* area = {};
t_grid_domain_decomp_info* decomp_info = {};
int* edge_blk = {};
int* edge_idx = {};
int* end_blk = {};
int* end_block = {};
int* end_index = {};
int* neighbor_blk = {};
int* neighbor_idx = {};
int* start_blk = {};
int* start_block = {};
int* start_index = {};
};


struct t_grid_edges {
    double* area_edge = {};
int* cell_blk = {};
int* cell_idx = {};
t_tangent_vectors** dual_normal_cell = {};
int* end_block = {};
int* end_index = {};
double* f_e = {};
double* fn_e = {};
double* ft_e = {};
double* inv_dual_edge_length = {};
double* inv_primal_edge_length = {};
t_tangent_vectors** primal_normal_cell = {};
int* quad_blk = {};
int* quad_idx = {};
int* refin_ctrl = {};
int* start_block = {};
int* start_index = {};
double* tangent_orientation = {};
int* vertex_blk = {};
int* vertex_idx = {};
};


struct t_grid_vertices {
    int* cell_blk = {};
int* cell_idx = {};
int* edge_blk = {};
int* edge_idx = {};
int* end_block = {};
int* end_index = {};
int* start_block = {};
int* start_index = {};
};


struct t_patch {
    t_grid_cells* cells = {};
t_grid_edges* edges = {};
t_grid_vertices* verts = {};
};


struct t_nh_metrics {
    int __f2dace_SA_bdy_halo_c_blk_d_0_s_460 = {};
int __f2dace_SA_bdy_halo_c_idx_d_0_s_459 = {};
int __f2dace_SA_coeff1_dwdz_d_0_s_407 = {};
int __f2dace_SA_coeff1_dwdz_d_1_s_408 = {};
int __f2dace_SA_coeff1_dwdz_d_2_s_409 = {};
int __f2dace_SA_coeff2_dwdz_d_0_s_410 = {};
int __f2dace_SA_coeff2_dwdz_d_1_s_411 = {};
int __f2dace_SA_coeff2_dwdz_d_2_s_412 = {};
int __f2dace_SA_coeff_gradekin_d_0_s_404 = {};
int __f2dace_SA_coeff_gradekin_d_1_s_405 = {};
int __f2dace_SA_coeff_gradekin_d_2_s_406 = {};
int __f2dace_SA_coeff_gradp_d_0_s_417 = {};
int __f2dace_SA_coeff_gradp_d_1_s_418 = {};
int __f2dace_SA_coeff_gradp_d_2_s_419 = {};
int __f2dace_SA_coeff_gradp_d_3_s_420 = {};
int __f2dace_SA_d2dexdz2_fac1_mc_d_0_s_445 = {};
int __f2dace_SA_d2dexdz2_fac1_mc_d_1_s_446 = {};
int __f2dace_SA_d2dexdz2_fac1_mc_d_2_s_447 = {};
int __f2dace_SA_d2dexdz2_fac2_mc_d_0_s_448 = {};
int __f2dace_SA_d2dexdz2_fac2_mc_d_1_s_449 = {};
int __f2dace_SA_d2dexdz2_fac2_mc_d_2_s_450 = {};
int __f2dace_SA_d_exner_dz_ref_ic_d_0_s_442 = {};
int __f2dace_SA_d_exner_dz_ref_ic_d_1_s_443 = {};
int __f2dace_SA_d_exner_dz_ref_ic_d_2_s_444 = {};
int __f2dace_SA_ddqz_z_full_e_d_0_s_380 = {};
int __f2dace_SA_ddqz_z_full_e_d_1_s_381 = {};
int __f2dace_SA_ddqz_z_full_e_d_2_s_382 = {};
int __f2dace_SA_ddqz_z_half_d_0_s_383 = {};
int __f2dace_SA_ddqz_z_half_d_1_s_384 = {};
int __f2dace_SA_ddqz_z_half_d_2_s_385 = {};
int __f2dace_SA_ddxn_z_full_d_0_s_374 = {};
int __f2dace_SA_ddxn_z_full_d_1_s_375 = {};
int __f2dace_SA_ddxn_z_full_d_2_s_376 = {};
int __f2dace_SA_ddxt_z_full_d_0_s_377 = {};
int __f2dace_SA_ddxt_z_full_d_1_s_378 = {};
int __f2dace_SA_ddxt_z_full_d_2_s_379 = {};
int __f2dace_SA_deepatmo_divh_mc_d_0_s_462 = {};
int __f2dace_SA_deepatmo_divzl_mc_d_0_s_465 = {};
int __f2dace_SA_deepatmo_divzu_mc_d_0_s_464 = {};
int __f2dace_SA_deepatmo_gradh_ifc_d_0_s_466 = {};
int __f2dace_SA_deepatmo_gradh_mc_d_0_s_461 = {};
int __f2dace_SA_deepatmo_invr_ifc_d_0_s_467 = {};
int __f2dace_SA_deepatmo_invr_mc_d_0_s_463 = {};
int __f2dace_SA_exner_exfac_d_0_s_421 = {};
int __f2dace_SA_exner_exfac_d_1_s_422 = {};
int __f2dace_SA_exner_exfac_d_2_s_423 = {};
int __f2dace_SA_exner_ref_mc_d_0_s_433 = {};
int __f2dace_SA_exner_ref_mc_d_1_s_434 = {};
int __f2dace_SA_exner_ref_mc_d_2_s_435 = {};
int __f2dace_SA_hmask_dd3d_d_0_s_368 = {};
int __f2dace_SA_hmask_dd3d_d_1_s_369 = {};
int __f2dace_SA_inv_ddqz_z_full_d_0_s_386 = {};
int __f2dace_SA_inv_ddqz_z_full_d_1_s_387 = {};
int __f2dace_SA_inv_ddqz_z_full_d_2_s_388 = {};
int __f2dace_SA_mask_prog_halo_c_d_0_s_468 = {};
int __f2dace_SA_mask_prog_halo_c_d_1_s_469 = {};
int __f2dace_SA_pg_edgeblk_d_0_s_457 = {};
int __f2dace_SA_pg_edgeidx_d_0_s_456 = {};
int __f2dace_SA_pg_exdist_d_0_s_451 = {};
int __f2dace_SA_pg_vertidx_d_0_s_458 = {};
int __f2dace_SA_rayleigh_vn_d_0_s_366 = {};
int __f2dace_SA_rayleigh_w_d_0_s_365 = {};
int __f2dace_SA_rho_ref_mc_d_0_s_436 = {};
int __f2dace_SA_rho_ref_mc_d_1_s_437 = {};
int __f2dace_SA_rho_ref_mc_d_2_s_438 = {};
int __f2dace_SA_rho_ref_me_d_0_s_439 = {};
int __f2dace_SA_rho_ref_me_d_1_s_440 = {};
int __f2dace_SA_rho_ref_me_d_2_s_441 = {};
int __f2dace_SA_scalfac_dd3d_d_0_s_367 = {};
int __f2dace_SA_theta_ref_ic_d_0_s_430 = {};
int __f2dace_SA_theta_ref_ic_d_1_s_431 = {};
int __f2dace_SA_theta_ref_ic_d_2_s_432 = {};
int __f2dace_SA_theta_ref_mc_d_0_s_424 = {};
int __f2dace_SA_theta_ref_mc_d_1_s_425 = {};
int __f2dace_SA_theta_ref_mc_d_2_s_426 = {};
int __f2dace_SA_theta_ref_me_d_0_s_427 = {};
int __f2dace_SA_theta_ref_me_d_1_s_428 = {};
int __f2dace_SA_theta_ref_me_d_2_s_429 = {};
int __f2dace_SA_vertidx_gradp_d_0_s_452 = {};
int __f2dace_SA_vertidx_gradp_d_1_s_453 = {};
int __f2dace_SA_vertidx_gradp_d_2_s_454 = {};
int __f2dace_SA_vertidx_gradp_d_3_s_455 = {};
int __f2dace_SA_vwind_expl_wgt_d_0_s_370 = {};
int __f2dace_SA_vwind_expl_wgt_d_1_s_371 = {};
int __f2dace_SA_vwind_impl_wgt_d_0_s_372 = {};
int __f2dace_SA_vwind_impl_wgt_d_1_s_373 = {};
int __f2dace_SA_wgtfac_c_d_0_s_389 = {};
int __f2dace_SA_wgtfac_c_d_1_s_390 = {};
int __f2dace_SA_wgtfac_c_d_2_s_391 = {};
int __f2dace_SA_wgtfac_e_d_0_s_392 = {};
int __f2dace_SA_wgtfac_e_d_1_s_393 = {};
int __f2dace_SA_wgtfac_e_d_2_s_394 = {};
int __f2dace_SA_wgtfacq1_c_d_0_s_401 = {};
int __f2dace_SA_wgtfacq1_c_d_1_s_402 = {};
int __f2dace_SA_wgtfacq1_c_d_2_s_403 = {};
int __f2dace_SA_wgtfacq_c_d_0_s_395 = {};
int __f2dace_SA_wgtfacq_c_d_1_s_396 = {};
int __f2dace_SA_wgtfacq_c_d_2_s_397 = {};
int __f2dace_SA_wgtfacq_e_d_0_s_398 = {};
int __f2dace_SA_wgtfacq_e_d_1_s_399 = {};
int __f2dace_SA_wgtfacq_e_d_2_s_400 = {};
int __f2dace_SA_zdiff_gradp_d_0_s_413 = {};
int __f2dace_SA_zdiff_gradp_d_1_s_414 = {};
int __f2dace_SA_zdiff_gradp_d_2_s_415 = {};
int __f2dace_SA_zdiff_gradp_d_3_s_416 = {};
int __f2dace_SOA_bdy_halo_c_blk_d_0_s_460 = {};
int __f2dace_SOA_bdy_halo_c_idx_d_0_s_459 = {};
int __f2dace_SOA_coeff1_dwdz_d_0_s_407 = {};
int __f2dace_SOA_coeff1_dwdz_d_1_s_408 = {};
int __f2dace_SOA_coeff1_dwdz_d_2_s_409 = {};
int __f2dace_SOA_coeff2_dwdz_d_0_s_410 = {};
int __f2dace_SOA_coeff2_dwdz_d_1_s_411 = {};
int __f2dace_SOA_coeff2_dwdz_d_2_s_412 = {};
int __f2dace_SOA_coeff_gradekin_d_0_s_404 = {};
int __f2dace_SOA_coeff_gradekin_d_1_s_405 = {};
int __f2dace_SOA_coeff_gradekin_d_2_s_406 = {};
int __f2dace_SOA_coeff_gradp_d_0_s_417 = {};
int __f2dace_SOA_coeff_gradp_d_1_s_418 = {};
int __f2dace_SOA_coeff_gradp_d_2_s_419 = {};
int __f2dace_SOA_coeff_gradp_d_3_s_420 = {};
int __f2dace_SOA_d2dexdz2_fac1_mc_d_0_s_445 = {};
int __f2dace_SOA_d2dexdz2_fac1_mc_d_1_s_446 = {};
int __f2dace_SOA_d2dexdz2_fac1_mc_d_2_s_447 = {};
int __f2dace_SOA_d2dexdz2_fac2_mc_d_0_s_448 = {};
int __f2dace_SOA_d2dexdz2_fac2_mc_d_1_s_449 = {};
int __f2dace_SOA_d2dexdz2_fac2_mc_d_2_s_450 = {};
int __f2dace_SOA_d_exner_dz_ref_ic_d_0_s_442 = {};
int __f2dace_SOA_d_exner_dz_ref_ic_d_1_s_443 = {};
int __f2dace_SOA_d_exner_dz_ref_ic_d_2_s_444 = {};
int __f2dace_SOA_ddqz_z_full_e_d_0_s_380 = {};
int __f2dace_SOA_ddqz_z_full_e_d_1_s_381 = {};
int __f2dace_SOA_ddqz_z_full_e_d_2_s_382 = {};
int __f2dace_SOA_ddqz_z_half_d_0_s_383 = {};
int __f2dace_SOA_ddqz_z_half_d_1_s_384 = {};
int __f2dace_SOA_ddqz_z_half_d_2_s_385 = {};
int __f2dace_SOA_ddxn_z_full_d_0_s_374 = {};
int __f2dace_SOA_ddxn_z_full_d_1_s_375 = {};
int __f2dace_SOA_ddxn_z_full_d_2_s_376 = {};
int __f2dace_SOA_ddxt_z_full_d_0_s_377 = {};
int __f2dace_SOA_ddxt_z_full_d_1_s_378 = {};
int __f2dace_SOA_ddxt_z_full_d_2_s_379 = {};
int __f2dace_SOA_deepatmo_divh_mc_d_0_s_462 = {};
int __f2dace_SOA_deepatmo_divzl_mc_d_0_s_465 = {};
int __f2dace_SOA_deepatmo_divzu_mc_d_0_s_464 = {};
int __f2dace_SOA_deepatmo_gradh_ifc_d_0_s_466 = {};
int __f2dace_SOA_deepatmo_gradh_mc_d_0_s_461 = {};
int __f2dace_SOA_deepatmo_invr_ifc_d_0_s_467 = {};
int __f2dace_SOA_deepatmo_invr_mc_d_0_s_463 = {};
int __f2dace_SOA_exner_exfac_d_0_s_421 = {};
int __f2dace_SOA_exner_exfac_d_1_s_422 = {};
int __f2dace_SOA_exner_exfac_d_2_s_423 = {};
int __f2dace_SOA_exner_ref_mc_d_0_s_433 = {};
int __f2dace_SOA_exner_ref_mc_d_1_s_434 = {};
int __f2dace_SOA_exner_ref_mc_d_2_s_435 = {};
int __f2dace_SOA_hmask_dd3d_d_0_s_368 = {};
int __f2dace_SOA_hmask_dd3d_d_1_s_369 = {};
int __f2dace_SOA_inv_ddqz_z_full_d_0_s_386 = {};
int __f2dace_SOA_inv_ddqz_z_full_d_1_s_387 = {};
int __f2dace_SOA_inv_ddqz_z_full_d_2_s_388 = {};
int __f2dace_SOA_mask_prog_halo_c_d_0_s_468 = {};
int __f2dace_SOA_mask_prog_halo_c_d_1_s_469 = {};
int __f2dace_SOA_pg_edgeblk_d_0_s_457 = {};
int __f2dace_SOA_pg_edgeidx_d_0_s_456 = {};
int __f2dace_SOA_pg_exdist_d_0_s_451 = {};
int __f2dace_SOA_pg_vertidx_d_0_s_458 = {};
int __f2dace_SOA_rayleigh_vn_d_0_s_366 = {};
int __f2dace_SOA_rayleigh_w_d_0_s_365 = {};
int __f2dace_SOA_rho_ref_mc_d_0_s_436 = {};
int __f2dace_SOA_rho_ref_mc_d_1_s_437 = {};
int __f2dace_SOA_rho_ref_mc_d_2_s_438 = {};
int __f2dace_SOA_rho_ref_me_d_0_s_439 = {};
int __f2dace_SOA_rho_ref_me_d_1_s_440 = {};
int __f2dace_SOA_rho_ref_me_d_2_s_441 = {};
int __f2dace_SOA_scalfac_dd3d_d_0_s_367 = {};
int __f2dace_SOA_theta_ref_ic_d_0_s_430 = {};
int __f2dace_SOA_theta_ref_ic_d_1_s_431 = {};
int __f2dace_SOA_theta_ref_ic_d_2_s_432 = {};
int __f2dace_SOA_theta_ref_mc_d_0_s_424 = {};
int __f2dace_SOA_theta_ref_mc_d_1_s_425 = {};
int __f2dace_SOA_theta_ref_mc_d_2_s_426 = {};
int __f2dace_SOA_theta_ref_me_d_0_s_427 = {};
int __f2dace_SOA_theta_ref_me_d_1_s_428 = {};
int __f2dace_SOA_theta_ref_me_d_2_s_429 = {};
int __f2dace_SOA_vertidx_gradp_d_0_s_452 = {};
int __f2dace_SOA_vertidx_gradp_d_1_s_453 = {};
int __f2dace_SOA_vertidx_gradp_d_2_s_454 = {};
int __f2dace_SOA_vertidx_gradp_d_3_s_455 = {};
int __f2dace_SOA_vwind_expl_wgt_d_0_s_370 = {};
int __f2dace_SOA_vwind_expl_wgt_d_1_s_371 = {};
int __f2dace_SOA_vwind_impl_wgt_d_0_s_372 = {};
int __f2dace_SOA_vwind_impl_wgt_d_1_s_373 = {};
int __f2dace_SOA_wgtfac_c_d_0_s_389 = {};
int __f2dace_SOA_wgtfac_c_d_1_s_390 = {};
int __f2dace_SOA_wgtfac_c_d_2_s_391 = {};
int __f2dace_SOA_wgtfac_e_d_0_s_392 = {};
int __f2dace_SOA_wgtfac_e_d_1_s_393 = {};
int __f2dace_SOA_wgtfac_e_d_2_s_394 = {};
int __f2dace_SOA_wgtfacq1_c_d_0_s_401 = {};
int __f2dace_SOA_wgtfacq1_c_d_1_s_402 = {};
int __f2dace_SOA_wgtfacq1_c_d_2_s_403 = {};
int __f2dace_SOA_wgtfacq_c_d_0_s_395 = {};
int __f2dace_SOA_wgtfacq_c_d_1_s_396 = {};
int __f2dace_SOA_wgtfacq_c_d_2_s_397 = {};
int __f2dace_SOA_wgtfacq_e_d_0_s_398 = {};
int __f2dace_SOA_wgtfacq_e_d_1_s_399 = {};
int __f2dace_SOA_wgtfacq_e_d_2_s_400 = {};
int __f2dace_SOA_zdiff_gradp_d_0_s_413 = {};
int __f2dace_SOA_zdiff_gradp_d_1_s_414 = {};
int __f2dace_SOA_zdiff_gradp_d_2_s_415 = {};
int __f2dace_SOA_zdiff_gradp_d_3_s_416 = {};
int* bdy_halo_c_blk = {};
int* bdy_halo_c_idx = {};
double* coeff1_dwdz = {};
double* coeff2_dwdz = {};
double* coeff_gradekin = {};
double* coeff_gradp = {};
double* d2dexdz2_fac1_mc = {};
double* d2dexdz2_fac2_mc = {};
double* d_exner_dz_ref_ic = {};
double* ddqz_z_full_e = {};
double* ddqz_z_half = {};
double* ddxn_z_full = {};
double* ddxt_z_full = {};
double* deepatmo_divh_mc = {};
double* deepatmo_divzl_mc = {};
double* deepatmo_divzu_mc = {};
double* deepatmo_gradh_ifc = {};
double* deepatmo_gradh_mc = {};
double* deepatmo_invr_ifc = {};
double* deepatmo_invr_mc = {};
double* exner_exfac = {};
double* exner_ref_mc = {};
double* hmask_dd3d = {};
double* inv_ddqz_z_full = {};
int* mask_prog_halo_c = {};
int* pg_edgeblk = {};
int* pg_edgeidx = {};
double* pg_exdist = {};
int* pg_vertidx = {};
double* rayleigh_vn = {};
double* rayleigh_w = {};
double* rho_ref_mc = {};
double* rho_ref_me = {};
double* scalfac_dd3d = {};
double* theta_ref_ic = {};
double* theta_ref_mc = {};
double* theta_ref_me = {};
int* vertidx_gradp = {};
double* vwind_expl_wgt = {};
double* vwind_impl_wgt = {};
double* wgtfac_c = {};
double* wgtfac_e = {};
double* wgtfacq1_c = {};
double* wgtfacq_c = {};
double* wgtfacq_e = {};
double* zdiff_gradp = {};
};


struct global_data_type {
    int __f2dace_SA_vct_a_d_0_s_1 = {};
int __f2dace_SOA_vct_a_d_0_s_1 = {};
double divdamp_fac = {};
double divdamp_fac2 = {};
double divdamp_fac3 = {};
double divdamp_fac4 = {};
double divdamp_fac_o2 = {};
int divdamp_order = {};
int divdamp_type = {};
double divdamp_z = {};
double divdamp_z2 = {};
double divdamp_z3 = {};
double divdamp_z4 = {};
int i_am_accel_node = {};
int iadv_rhotheta = {};
double iau_wgt_dyn = {};
int igradp_method = {};
int is_iau_active = {};
int itime_scheme = {};
int* kstart_dd3d = {};
int* kstart_moist = {};
int l_limited_area = {};
int ldeepatmo_var_0 = {};
int lextra_diffu = {};
int* ndyn_substeps_var = {};
int* nflat_gradp = {};
int* nflatlev = {};
int nproma_var_103 = {};
int* nrdmax = {};
double nudge_max_coeff = {};
int p_test_run = {};
int process_mpi_all_size = {};
int rayleigh_type = {};
double rhotheta_offctr = {};
int timer_intp = {};
int timer_solve_nh_cellcomp = {};
int timer_solve_nh_exch = {};
int timer_solve_nh_veltend = {};
int timers_level = {};
double* vct_a = {};
double veladv_offctr = {};
};


struct t_nh_prog {
    int __f2dace_SA_exner_d_0_s_291 = {};
int __f2dace_SA_exner_d_1_s_292 = {};
int __f2dace_SA_exner_d_2_s_293 = {};
int __f2dace_SA_rho_d_0_s_288 = {};
int __f2dace_SA_rho_d_1_s_289 = {};
int __f2dace_SA_rho_d_2_s_290 = {};
int __f2dace_SA_theta_v_d_0_s_294 = {};
int __f2dace_SA_theta_v_d_1_s_295 = {};
int __f2dace_SA_theta_v_d_2_s_296 = {};
int __f2dace_SA_vn_d_0_s_285 = {};
int __f2dace_SA_vn_d_1_s_286 = {};
int __f2dace_SA_vn_d_2_s_287 = {};
int __f2dace_SA_w_d_0_s_282 = {};
int __f2dace_SA_w_d_1_s_283 = {};
int __f2dace_SA_w_d_2_s_284 = {};
int __f2dace_SOA_exner_d_0_s_291 = {};
int __f2dace_SOA_exner_d_1_s_292 = {};
int __f2dace_SOA_exner_d_2_s_293 = {};
int __f2dace_SOA_rho_d_0_s_288 = {};
int __f2dace_SOA_rho_d_1_s_289 = {};
int __f2dace_SOA_rho_d_2_s_290 = {};
int __f2dace_SOA_theta_v_d_0_s_294 = {};
int __f2dace_SOA_theta_v_d_1_s_295 = {};
int __f2dace_SOA_theta_v_d_2_s_296 = {};
int __f2dace_SOA_vn_d_0_s_285 = {};
int __f2dace_SOA_vn_d_1_s_286 = {};
int __f2dace_SOA_vn_d_2_s_287 = {};
int __f2dace_SOA_w_d_0_s_282 = {};
int __f2dace_SOA_w_d_1_s_283 = {};
int __f2dace_SOA_w_d_2_s_284 = {};
double* exner = {};
double* rho = {};
double* theta_v = {};
double* vn = {};
double* w = {};
};


struct t_nh_diag {
    int __f2dace_SA_ddt_exner_phy_d_0_s_333 = {};
int __f2dace_SA_ddt_exner_phy_d_1_s_334 = {};
int __f2dace_SA_ddt_exner_phy_d_2_s_335 = {};
int __f2dace_SA_ddt_vn_apc_pc_d_0_s_351 = {};
int __f2dace_SA_ddt_vn_apc_pc_d_1_s_352 = {};
int __f2dace_SA_ddt_vn_apc_pc_d_2_s_353 = {};
int __f2dace_SA_ddt_vn_apc_pc_d_3_s_354 = {};
int __f2dace_SA_ddt_vn_phy_d_0_s_336 = {};
int __f2dace_SA_ddt_vn_phy_d_1_s_337 = {};
int __f2dace_SA_ddt_vn_phy_d_2_s_338 = {};
int __f2dace_SA_ddt_w_adv_pc_d_0_s_355 = {};
int __f2dace_SA_ddt_w_adv_pc_d_1_s_356 = {};
int __f2dace_SA_ddt_w_adv_pc_d_2_s_357 = {};
int __f2dace_SA_ddt_w_adv_pc_d_3_s_358 = {};
int __f2dace_SA_exner_dyn_incr_d_0_s_339 = {};
int __f2dace_SA_exner_dyn_incr_d_1_s_340 = {};
int __f2dace_SA_exner_dyn_incr_d_2_s_341 = {};
int __f2dace_SA_exner_incr_d_0_s_324 = {};
int __f2dace_SA_exner_incr_d_1_s_325 = {};
int __f2dace_SA_exner_incr_d_2_s_326 = {};
int __f2dace_SA_exner_pr_d_0_s_297 = {};
int __f2dace_SA_exner_pr_d_1_s_298 = {};
int __f2dace_SA_exner_pr_d_2_s_299 = {};
int __f2dace_SA_grf_tend_rho_d_0_s_315 = {};
int __f2dace_SA_grf_tend_rho_d_1_s_316 = {};
int __f2dace_SA_grf_tend_rho_d_2_s_317 = {};
int __f2dace_SA_grf_tend_thv_d_0_s_318 = {};
int __f2dace_SA_grf_tend_thv_d_1_s_319 = {};
int __f2dace_SA_grf_tend_thv_d_2_s_320 = {};
int __f2dace_SA_grf_tend_vn_d_0_s_309 = {};
int __f2dace_SA_grf_tend_vn_d_1_s_310 = {};
int __f2dace_SA_grf_tend_vn_d_2_s_311 = {};
int __f2dace_SA_grf_tend_w_d_0_s_312 = {};
int __f2dace_SA_grf_tend_w_d_1_s_313 = {};
int __f2dace_SA_grf_tend_w_d_2_s_314 = {};
int __f2dace_SA_mass_fl_e_d_0_s_300 = {};
int __f2dace_SA_mass_fl_e_d_1_s_301 = {};
int __f2dace_SA_mass_fl_e_d_2_s_302 = {};
int __f2dace_SA_mass_fl_e_sv_d_0_s_348 = {};
int __f2dace_SA_mass_fl_e_sv_d_1_s_349 = {};
int __f2dace_SA_mass_fl_e_sv_d_2_s_350 = {};
int __f2dace_SA_rho_ic_d_0_s_303 = {};
int __f2dace_SA_rho_ic_d_1_s_304 = {};
int __f2dace_SA_rho_ic_d_2_s_305 = {};
int __f2dace_SA_rho_incr_d_0_s_327 = {};
int __f2dace_SA_rho_incr_d_1_s_328 = {};
int __f2dace_SA_rho_incr_d_2_s_329 = {};
int __f2dace_SA_theta_v_ic_d_0_s_306 = {};
int __f2dace_SA_theta_v_ic_d_1_s_307 = {};
int __f2dace_SA_theta_v_ic_d_2_s_308 = {};
int __f2dace_SA_vn_ie_d_0_s_342 = {};
int __f2dace_SA_vn_ie_d_1_s_343 = {};
int __f2dace_SA_vn_ie_d_2_s_344 = {};
int __f2dace_SA_vn_incr_d_0_s_321 = {};
int __f2dace_SA_vn_incr_d_1_s_322 = {};
int __f2dace_SA_vn_incr_d_2_s_323 = {};
int __f2dace_SA_vt_d_0_s_330 = {};
int __f2dace_SA_vt_d_1_s_331 = {};
int __f2dace_SA_vt_d_2_s_332 = {};
int __f2dace_SA_w_concorr_c_d_0_s_345 = {};
int __f2dace_SA_w_concorr_c_d_1_s_346 = {};
int __f2dace_SA_w_concorr_c_d_2_s_347 = {};
int __f2dace_SOA_ddt_exner_phy_d_0_s_333 = {};
int __f2dace_SOA_ddt_exner_phy_d_1_s_334 = {};
int __f2dace_SOA_ddt_exner_phy_d_2_s_335 = {};
int __f2dace_SOA_ddt_vn_apc_pc_d_0_s_351 = {};
int __f2dace_SOA_ddt_vn_apc_pc_d_1_s_352 = {};
int __f2dace_SOA_ddt_vn_apc_pc_d_2_s_353 = {};
int __f2dace_SOA_ddt_vn_apc_pc_d_3_s_354 = {};
int __f2dace_SOA_ddt_vn_phy_d_0_s_336 = {};
int __f2dace_SOA_ddt_vn_phy_d_1_s_337 = {};
int __f2dace_SOA_ddt_vn_phy_d_2_s_338 = {};
int __f2dace_SOA_ddt_w_adv_pc_d_0_s_355 = {};
int __f2dace_SOA_ddt_w_adv_pc_d_1_s_356 = {};
int __f2dace_SOA_ddt_w_adv_pc_d_2_s_357 = {};
int __f2dace_SOA_ddt_w_adv_pc_d_3_s_358 = {};
int __f2dace_SOA_exner_dyn_incr_d_0_s_339 = {};
int __f2dace_SOA_exner_dyn_incr_d_1_s_340 = {};
int __f2dace_SOA_exner_dyn_incr_d_2_s_341 = {};
int __f2dace_SOA_exner_incr_d_0_s_324 = {};
int __f2dace_SOA_exner_incr_d_1_s_325 = {};
int __f2dace_SOA_exner_incr_d_2_s_326 = {};
int __f2dace_SOA_exner_pr_d_0_s_297 = {};
int __f2dace_SOA_exner_pr_d_1_s_298 = {};
int __f2dace_SOA_exner_pr_d_2_s_299 = {};
int __f2dace_SOA_grf_tend_rho_d_0_s_315 = {};
int __f2dace_SOA_grf_tend_rho_d_1_s_316 = {};
int __f2dace_SOA_grf_tend_rho_d_2_s_317 = {};
int __f2dace_SOA_grf_tend_thv_d_0_s_318 = {};
int __f2dace_SOA_grf_tend_thv_d_1_s_319 = {};
int __f2dace_SOA_grf_tend_thv_d_2_s_320 = {};
int __f2dace_SOA_grf_tend_vn_d_0_s_309 = {};
int __f2dace_SOA_grf_tend_vn_d_1_s_310 = {};
int __f2dace_SOA_grf_tend_vn_d_2_s_311 = {};
int __f2dace_SOA_grf_tend_w_d_0_s_312 = {};
int __f2dace_SOA_grf_tend_w_d_1_s_313 = {};
int __f2dace_SOA_grf_tend_w_d_2_s_314 = {};
int __f2dace_SOA_mass_fl_e_d_0_s_300 = {};
int __f2dace_SOA_mass_fl_e_d_1_s_301 = {};
int __f2dace_SOA_mass_fl_e_d_2_s_302 = {};
int __f2dace_SOA_mass_fl_e_sv_d_0_s_348 = {};
int __f2dace_SOA_mass_fl_e_sv_d_1_s_349 = {};
int __f2dace_SOA_mass_fl_e_sv_d_2_s_350 = {};
int __f2dace_SOA_rho_ic_d_0_s_303 = {};
int __f2dace_SOA_rho_ic_d_1_s_304 = {};
int __f2dace_SOA_rho_ic_d_2_s_305 = {};
int __f2dace_SOA_rho_incr_d_0_s_327 = {};
int __f2dace_SOA_rho_incr_d_1_s_328 = {};
int __f2dace_SOA_rho_incr_d_2_s_329 = {};
int __f2dace_SOA_theta_v_ic_d_0_s_306 = {};
int __f2dace_SOA_theta_v_ic_d_1_s_307 = {};
int __f2dace_SOA_theta_v_ic_d_2_s_308 = {};
int __f2dace_SOA_vn_ie_d_0_s_342 = {};
int __f2dace_SOA_vn_ie_d_1_s_343 = {};
int __f2dace_SOA_vn_ie_d_2_s_344 = {};
int __f2dace_SOA_vn_incr_d_0_s_321 = {};
int __f2dace_SOA_vn_incr_d_1_s_322 = {};
int __f2dace_SOA_vn_incr_d_2_s_323 = {};
int __f2dace_SOA_vt_d_0_s_330 = {};
int __f2dace_SOA_vt_d_1_s_331 = {};
int __f2dace_SOA_vt_d_2_s_332 = {};
int __f2dace_SOA_w_concorr_c_d_0_s_345 = {};
int __f2dace_SOA_w_concorr_c_d_1_s_346 = {};
int __f2dace_SOA_w_concorr_c_d_2_s_347 = {};
double* ddt_exner_phy = {};
double* ddt_vn_apc_pc = {};
double* ddt_vn_phy = {};
double* ddt_w_adv_pc = {};
double* exner_dyn_incr = {};
double* exner_incr = {};
double* exner_pr = {};
double* grf_tend_rho = {};
double* grf_tend_thv = {};
double* grf_tend_vn = {};
double* grf_tend_w = {};
double* mass_fl_e = {};
double* mass_fl_e_sv = {};
double max_vcfl_dyn = {};
double* rho_ic = {};
double* rho_incr = {};
double* theta_v_ic = {};
double* vn_ie = {};
double* vn_incr = {};
double* vt = {};
double* w_concorr_c = {};
};


struct t_nh_ref {
    int __f2dace_SA_vn_ref_d_0_s_359 = {};
int __f2dace_SA_vn_ref_d_1_s_360 = {};
int __f2dace_SA_vn_ref_d_2_s_361 = {};
int __f2dace_SA_w_ref_d_0_s_362 = {};
int __f2dace_SA_w_ref_d_1_s_363 = {};
int __f2dace_SA_w_ref_d_2_s_364 = {};
int __f2dace_SOA_vn_ref_d_0_s_359 = {};
int __f2dace_SOA_vn_ref_d_1_s_360 = {};
int __f2dace_SOA_vn_ref_d_2_s_361 = {};
int __f2dace_SOA_w_ref_d_0_s_362 = {};
int __f2dace_SOA_w_ref_d_1_s_363 = {};
int __f2dace_SOA_w_ref_d_2_s_364 = {};
double* vn_ref = {};
double* w_ref = {};
};


struct t_nh_state {
    t_nh_diag* diag = {};
t_nh_metrics* metrics = {};
t_nh_prog** prog = {};
t_nh_ref* ref = {};
};


struct t_prepare_adv {
    int __f2dace_SA_mass_flx_ic_d_0_s_485 = {};
int __f2dace_SA_mass_flx_ic_d_1_s_486 = {};
int __f2dace_SA_mass_flx_ic_d_2_s_487 = {};
int __f2dace_SA_mass_flx_me_d_0_s_482 = {};
int __f2dace_SA_mass_flx_me_d_1_s_483 = {};
int __f2dace_SA_mass_flx_me_d_2_s_484 = {};
int __f2dace_SA_vn_traj_d_0_s_491 = {};
int __f2dace_SA_vn_traj_d_1_s_492 = {};
int __f2dace_SA_vn_traj_d_2_s_493 = {};
int __f2dace_SA_vol_flx_ic_d_0_s_488 = {};
int __f2dace_SA_vol_flx_ic_d_1_s_489 = {};
int __f2dace_SA_vol_flx_ic_d_2_s_490 = {};
int __f2dace_SOA_mass_flx_ic_d_0_s_485 = {};
int __f2dace_SOA_mass_flx_ic_d_1_s_486 = {};
int __f2dace_SOA_mass_flx_ic_d_2_s_487 = {};
int __f2dace_SOA_mass_flx_me_d_0_s_482 = {};
int __f2dace_SOA_mass_flx_me_d_1_s_483 = {};
int __f2dace_SOA_mass_flx_me_d_2_s_484 = {};
int __f2dace_SOA_vn_traj_d_0_s_491 = {};
int __f2dace_SOA_vn_traj_d_1_s_492 = {};
int __f2dace_SOA_vn_traj_d_2_s_493 = {};
int __f2dace_SOA_vol_flx_ic_d_0_s_488 = {};
int __f2dace_SOA_vol_flx_ic_d_1_s_489 = {};
int __f2dace_SOA_vol_flx_ic_d_2_s_490 = {};
double* mass_flx_ic = {};
double* mass_flx_me = {};
double* vn_traj = {};
double* vol_flx_ic = {};
};




struct solve_nh_state_t;  // Forward declaration.

DACE_EXPORTED solve_nh_state_t *__dace_init_solve_nh(global_data_type* global_data, t_int_state* p_int, t_nh_state* p_nh, t_patch* p_patch, t_prepare_adv* prep_adv, int __f2dace_OPTIONAL_lacc, double dtime, int idyn_timestep, int jstep, int l_init, int l_recompute, int lacc, int lclean_mflx, int lprep_adv, int lsave_mflx, int nnew, int nnow, int tmp_index_1292, int tmp_index_1293);
DACE_EXPORTED int __dace_exit_solve_nh(solve_nh_state_t *__state);
DACE_EXPORTED void __program_solve_nh(solve_nh_state_t *__state, global_data_type* global_data, t_int_state* p_int, t_nh_state* p_nh, t_patch* p_patch, t_prepare_adv* prep_adv, int __f2dace_OPTIONAL_lacc, double dtime, int idyn_timestep, int jstep, int l_init, int l_recompute, int lacc, int lclean_mflx, int lprep_adv, int lsave_mflx, int nnew, int nnow, int tmp_index_1292, int tmp_index_1293);

#endif // __DACE_CODEGEN_SOLVE_NH__
