
#ifndef __VELOCITY_SHIM_H__
#define __VELOCITY_SHIM_H__

#include "shared_struct_defs.h"
#include <dace/dace.h>

#if defined(GPU)

#error "GPU Implementation TODO"

#else

#include "velocity.h"

static velocity_no_nproma_if_prop_lvn_only_1_istep_1_state_t *state_lvn_only_1_istep_1 = nullptr;
static velocity_no_nproma_if_prop_lvn_only_1_istep_2_state_t *state_lvn_only_1_istep_2 = nullptr;
static velocity_no_nproma_if_prop_lvn_only_0_istep_1_state_t *state_lvn_only_0_istep_1 = nullptr;
static velocity_no_nproma_if_prop_lvn_only_0_istep_2_state_t *state_lvn_only_0_istep_2 = nullptr;

static void velocity_tendencies(
    int * __CG_global_data__m_nflatlev,
        int * __CG_global_data__m_nrdmax,
        double * __CG_p_diag__m_ddt_vn_apc_pc,
        double * __CG_p_diag__m_ddt_w_adv_pc,
        double * __CG_p_diag__m_vn_ie,
        double * __CG_p_diag__m_vt,
        double * __CG_p_diag__m_w_concorr_c,
        double * __CG_p_int__m_c_lin_e,
        double * __CG_p_int__m_cells_aw_verts,
        double * __CG_p_int__m_e_bln_c_s,
        double * __CG_p_int__m_geofac_grdiv,
        double * __CG_p_int__m_geofac_n2s,
        double * __CG_p_int__m_geofac_rot,
        double * __CG_p_int__m_rbf_vec_coeff_e,
        double * __CG_p_metrics__m_coeff1_dwdz,
        double * __CG_p_metrics__m_coeff2_dwdz,
        double * __CG_p_metrics__m_coeff_gradekin,
        double * __CG_p_metrics__m_ddqz_z_full_e,
        double * __CG_p_metrics__m_ddqz_z_half,
        double * __CG_p_metrics__m_ddxn_z_full,
        double * __CG_p_metrics__m_ddxt_z_full,
        double * __CG_p_metrics__m_wgtfac_c,
        double * __CG_p_metrics__m_wgtfac_e,
        double * __CG_p_metrics__m_wgtfacq_e,
        int * __CG_p_patch__CG_cells__CG_decomp_info__m_owner_mask,
        double * __CG_p_patch__CG_cells__m_area,
        int * __CG_p_patch__CG_cells__m_edge_blk,
        int * __CG_p_patch__CG_cells__m_edge_idx,
        int * __CG_p_patch__CG_cells__m_end_block,
        int * __CG_p_patch__CG_cells__m_end_index,
        int * __CG_p_patch__CG_cells__m_neighbor_blk,
        int * __CG_p_patch__CG_cells__m_neighbor_idx,
        int * __CG_p_patch__CG_cells__m_start_block,
        int * __CG_p_patch__CG_cells__m_start_index,
        double * __CG_p_patch__CG_edges__m_area_edge,
        int * __CG_p_patch__CG_edges__m_cell_blk,
        int * __CG_p_patch__CG_edges__m_cell_idx,
        int * __CG_p_patch__CG_edges__m_end_block,
        int * __CG_p_patch__CG_edges__m_end_index,
        double * __CG_p_patch__CG_edges__m_f_e,
        double * __CG_p_patch__CG_edges__m_inv_dual_edge_length,
        double * __CG_p_patch__CG_edges__m_inv_primal_edge_length,
        int * __CG_p_patch__CG_edges__m_quad_blk,
        int * __CG_p_patch__CG_edges__m_quad_idx,
        int * __CG_p_patch__CG_edges__m_start_block,
        int * __CG_p_patch__CG_edges__m_start_index,
        double * __CG_p_patch__CG_edges__m_tangent_orientation,
        int * __CG_p_patch__CG_edges__m_vertex_blk,
        int * __CG_p_patch__CG_edges__m_vertex_idx,
        int * __CG_p_patch__CG_verts__m_cell_blk,
        int * __CG_p_patch__CG_verts__m_cell_idx,
        int * __CG_p_patch__CG_verts__m_edge_blk,
        int * __CG_p_patch__CG_verts__m_edge_idx,
        int * __CG_p_patch__CG_verts__m_end_block,
        int * __CG_p_patch__CG_verts__m_end_index,
        int * __CG_p_patch__CG_verts__m_start_block,
        int * __CG_p_patch__CG_verts__m_start_index,
        double * __CG_p_prog__m_vn,
        double * __CG_p_prog__m_w,
        global_data_type * global_data,
        t_nh_diag * p_diag,
        t_int_state * p_int,
        t_nh_metrics * p_metrics,
        t_patch * p_patch,
        t_nh_prog * p_prog,
        double * z_kin_hor_e,
        double * z_vt_ie,
        double * z_w_concorr_me,
        int __CG_global_data__m_nproma,
        double & __CG_p_diag__m_max_vcfl_dyn,
        int __f2dace_A_z_kin_hor_e_d_0_s,
        int __f2dace_A_z_kin_hor_e_d_1_s,
        int __f2dace_A_z_vt_ie_d_0_s,
        int __f2dace_A_z_vt_ie_d_1_s,
        int __f2dace_A_z_w_concorr_me_d_0_s,
        int __f2dace_A_z_w_concorr_me_d_1_s,
        int __f2dace_OA_z_kin_hor_e_d_0_s,
        int __f2dace_OA_z_kin_hor_e_d_1_s,
        int __f2dace_OA_z_kin_hor_e_d_2_s,
        int __f2dace_OA_z_vt_ie_d_0_s,
        int __f2dace_OA_z_vt_ie_d_1_s,
        int __f2dace_OA_z_vt_ie_d_2_s,
        int __f2dace_OA_z_w_concorr_me_d_0_s,
        int __f2dace_OA_z_w_concorr_me_d_1_s,
        int __f2dace_OA_z_w_concorr_me_d_2_s,
        double dt_linintp_ubc,
        double dtime,
        int istep,
        int ldeepatmo,
        int lvn_only,
        int ntnd
){
    static int lvn_only_1_istep_1_call_id = 0;
    static int lvn_only_1_istep_2_call_id = 0;
    static int lvn_only_0_istep_1_call_id = 0;
    static int lvn_only_0_istep_2_call_id = 0;

    if (lvn_only == 1 && istep == 1) {
        if (lvn_only_1_istep_1_call_id == 0) {
            state_lvn_only_1_istep_1 = __dace_init_velocity_no_nproma_if_prop_lvn_only_1_istep_1(
                __CG_global_data__m_nflatlev,
            __CG_global_data__m_nrdmax,
            __CG_p_diag__m_ddt_vn_apc_pc,
            __CG_p_diag__m_vn_ie,
            __CG_p_diag__m_vt,
            __CG_p_diag__m_w_concorr_c,
            __CG_p_int__m_c_lin_e,
            __CG_p_int__m_e_bln_c_s,
            __CG_p_int__m_geofac_grdiv,
            __CG_p_int__m_geofac_rot,
            __CG_p_int__m_rbf_vec_coeff_e,
            __CG_p_metrics__m_coeff_gradekin,
            __CG_p_metrics__m_ddqz_z_full_e,
            __CG_p_metrics__m_ddqz_z_half,
            __CG_p_metrics__m_ddxn_z_full,
            __CG_p_metrics__m_ddxt_z_full,
            __CG_p_metrics__m_wgtfac_c,
            __CG_p_metrics__m_wgtfac_e,
            __CG_p_metrics__m_wgtfacq_e,
            __CG_p_patch__CG_cells__m_edge_blk,
            __CG_p_patch__CG_cells__m_edge_idx,
            __CG_p_patch__CG_cells__m_end_block,
            __CG_p_patch__CG_cells__m_end_index,
            __CG_p_patch__CG_cells__m_start_block,
            __CG_p_patch__CG_cells__m_start_index,
            __CG_p_patch__CG_edges__m_area_edge,
            __CG_p_patch__CG_edges__m_cell_blk,
            __CG_p_patch__CG_edges__m_cell_idx,
            __CG_p_patch__CG_edges__m_end_block,
            __CG_p_patch__CG_edges__m_end_index,
            __CG_p_patch__CG_edges__m_f_e,
            __CG_p_patch__CG_edges__m_inv_primal_edge_length,
            __CG_p_patch__CG_edges__m_quad_blk,
            __CG_p_patch__CG_edges__m_quad_idx,
            __CG_p_patch__CG_edges__m_start_block,
            __CG_p_patch__CG_edges__m_start_index,
            __CG_p_patch__CG_edges__m_tangent_orientation,
            __CG_p_patch__CG_edges__m_vertex_blk,
            __CG_p_patch__CG_edges__m_vertex_idx,
            __CG_p_patch__CG_verts__m_edge_blk,
            __CG_p_patch__CG_verts__m_edge_idx,
            __CG_p_patch__CG_verts__m_end_block,
            __CG_p_patch__CG_verts__m_end_index,
            __CG_p_patch__CG_verts__m_start_block,
            __CG_p_patch__CG_verts__m_start_index,
            __CG_p_prog__m_vn,
            __CG_p_prog__m_w,
            global_data,
            p_diag,
            p_int,
            p_metrics,
            p_patch,
            p_prog,
            z_kin_hor_e,
            z_vt_ie,
            z_w_concorr_me,
            __CG_global_data__m_nproma,
            __CG_p_diag__m_max_vcfl_dyn,
            __f2dace_A_z_kin_hor_e_d_0_s,
            __f2dace_A_z_kin_hor_e_d_1_s,
            __f2dace_A_z_vt_ie_d_0_s,
            __f2dace_A_z_vt_ie_d_1_s,
            __f2dace_A_z_w_concorr_me_d_0_s,
            __f2dace_A_z_w_concorr_me_d_1_s,
            __f2dace_OA_z_kin_hor_e_d_0_s,
            __f2dace_OA_z_kin_hor_e_d_1_s,
            __f2dace_OA_z_kin_hor_e_d_2_s,
            __f2dace_OA_z_vt_ie_d_0_s,
            __f2dace_OA_z_vt_ie_d_1_s,
            __f2dace_OA_z_vt_ie_d_2_s,
            __f2dace_OA_z_w_concorr_me_d_0_s,
            __f2dace_OA_z_w_concorr_me_d_1_s,
            __f2dace_OA_z_w_concorr_me_d_2_s,
            dt_linintp_ubc,
            dtime,
            istep,
            ldeepatmo,
            lvn_only,
            ntnd
            );
        }
        lvn_only_1_istep_1_call_id++;
        __program_velocity_no_nproma_if_prop_lvn_only_1_istep_1(
            state_lvn_only_1_istep_1,
            __CG_global_data__m_nflatlev,
            __CG_global_data__m_nrdmax,
            __CG_p_diag__m_ddt_vn_apc_pc,
            __CG_p_diag__m_vn_ie,
            __CG_p_diag__m_vt,
            __CG_p_diag__m_w_concorr_c,
            __CG_p_int__m_c_lin_e,
            __CG_p_int__m_e_bln_c_s,
            __CG_p_int__m_geofac_grdiv,
            __CG_p_int__m_geofac_rot,
            __CG_p_int__m_rbf_vec_coeff_e,
            __CG_p_metrics__m_coeff_gradekin,
            __CG_p_metrics__m_ddqz_z_full_e,
            __CG_p_metrics__m_ddqz_z_half,
            __CG_p_metrics__m_ddxn_z_full,
            __CG_p_metrics__m_ddxt_z_full,
            __CG_p_metrics__m_wgtfac_c,
            __CG_p_metrics__m_wgtfac_e,
            __CG_p_metrics__m_wgtfacq_e,
            __CG_p_patch__CG_cells__m_edge_blk,
            __CG_p_patch__CG_cells__m_edge_idx,
            __CG_p_patch__CG_cells__m_end_block,
            __CG_p_patch__CG_cells__m_end_index,
            __CG_p_patch__CG_cells__m_start_block,
            __CG_p_patch__CG_cells__m_start_index,
            __CG_p_patch__CG_edges__m_area_edge,
            __CG_p_patch__CG_edges__m_cell_blk,
            __CG_p_patch__CG_edges__m_cell_idx,
            __CG_p_patch__CG_edges__m_end_block,
            __CG_p_patch__CG_edges__m_end_index,
            __CG_p_patch__CG_edges__m_f_e,
            __CG_p_patch__CG_edges__m_inv_primal_edge_length,
            __CG_p_patch__CG_edges__m_quad_blk,
            __CG_p_patch__CG_edges__m_quad_idx,
            __CG_p_patch__CG_edges__m_start_block,
            __CG_p_patch__CG_edges__m_start_index,
            __CG_p_patch__CG_edges__m_tangent_orientation,
            __CG_p_patch__CG_edges__m_vertex_blk,
            __CG_p_patch__CG_edges__m_vertex_idx,
            __CG_p_patch__CG_verts__m_edge_blk,
            __CG_p_patch__CG_verts__m_edge_idx,
            __CG_p_patch__CG_verts__m_end_block,
            __CG_p_patch__CG_verts__m_end_index,
            __CG_p_patch__CG_verts__m_start_block,
            __CG_p_patch__CG_verts__m_start_index,
            __CG_p_prog__m_vn,
            __CG_p_prog__m_w,
            global_data,
            p_diag,
            p_int,
            p_metrics,
            p_patch,
            p_prog,
            z_kin_hor_e,
            z_vt_ie,
            z_w_concorr_me,
            __CG_global_data__m_nproma,
            __CG_p_diag__m_max_vcfl_dyn,
            __f2dace_A_z_kin_hor_e_d_0_s,
            __f2dace_A_z_kin_hor_e_d_1_s,
            __f2dace_A_z_vt_ie_d_0_s,
            __f2dace_A_z_vt_ie_d_1_s,
            __f2dace_A_z_w_concorr_me_d_0_s,
            __f2dace_A_z_w_concorr_me_d_1_s,
            __f2dace_OA_z_kin_hor_e_d_0_s,
            __f2dace_OA_z_kin_hor_e_d_1_s,
            __f2dace_OA_z_kin_hor_e_d_2_s,
            __f2dace_OA_z_vt_ie_d_0_s,
            __f2dace_OA_z_vt_ie_d_1_s,
            __f2dace_OA_z_vt_ie_d_2_s,
            __f2dace_OA_z_w_concorr_me_d_0_s,
            __f2dace_OA_z_w_concorr_me_d_1_s,
            __f2dace_OA_z_w_concorr_me_d_2_s,
            dt_linintp_ubc,
            dtime,
            istep,
            ldeepatmo,
            lvn_only,
            ntnd
        );
    } else if (lvn_only == 1 && istep == 2) {
        if (lvn_only_1_istep_2_call_id == 0) {
            state_lvn_only_1_istep_2 = __dace_init_velocity_no_nproma_if_prop_lvn_only_1_istep_2(
            __CG_global_data__m_nflatlev,
            __CG_global_data__m_nrdmax,
            __CG_p_diag__m_ddt_vn_apc_pc,
            __CG_p_diag__m_vn_ie,
            __CG_p_diag__m_vt,
            __CG_p_diag__m_w_concorr_c,
            __CG_p_int__m_c_lin_e,
            __CG_p_int__m_e_bln_c_s,
            __CG_p_int__m_geofac_grdiv,
            __CG_p_int__m_geofac_rot,
            __CG_p_metrics__m_coeff_gradekin,
            __CG_p_metrics__m_ddqz_z_full_e,
            __CG_p_metrics__m_ddqz_z_half,
            __CG_p_patch__CG_cells__m_edge_blk,
            __CG_p_patch__CG_cells__m_edge_idx,
            __CG_p_patch__CG_cells__m_end_block,
            __CG_p_patch__CG_cells__m_end_index,
            __CG_p_patch__CG_cells__m_start_block,
            __CG_p_patch__CG_cells__m_start_index,
            __CG_p_patch__CG_edges__m_area_edge,
            __CG_p_patch__CG_edges__m_cell_blk,
            __CG_p_patch__CG_edges__m_cell_idx,
            __CG_p_patch__CG_edges__m_end_block,
            __CG_p_patch__CG_edges__m_end_index,
            __CG_p_patch__CG_edges__m_f_e,
            __CG_p_patch__CG_edges__m_inv_primal_edge_length,
            __CG_p_patch__CG_edges__m_quad_blk,
            __CG_p_patch__CG_edges__m_quad_idx,
            __CG_p_patch__CG_edges__m_start_block,
            __CG_p_patch__CG_edges__m_start_index,
            __CG_p_patch__CG_edges__m_tangent_orientation,
            __CG_p_patch__CG_edges__m_vertex_blk,
            __CG_p_patch__CG_edges__m_vertex_idx,
            __CG_p_patch__CG_verts__m_edge_blk,
            __CG_p_patch__CG_verts__m_edge_idx,
            __CG_p_patch__CG_verts__m_end_block,
            __CG_p_patch__CG_verts__m_end_index,
            __CG_p_patch__CG_verts__m_start_block,
            __CG_p_patch__CG_verts__m_start_index,
            __CG_p_prog__m_vn,
            __CG_p_prog__m_w,
            global_data,
            p_diag,
            p_int,
            p_metrics,
            p_patch,
            p_prog,
            z_kin_hor_e,
            z_vt_ie,
            z_w_concorr_me,
            __CG_global_data__m_nproma,
            __CG_p_diag__m_max_vcfl_dyn,
            __f2dace_A_z_kin_hor_e_d_0_s,
            __f2dace_A_z_kin_hor_e_d_1_s,
            __f2dace_OA_z_kin_hor_e_d_0_s,
            __f2dace_OA_z_kin_hor_e_d_1_s,
            __f2dace_OA_z_kin_hor_e_d_2_s,
            dt_linintp_ubc,
            dtime,
            istep,
            ldeepatmo,
            lvn_only,
            ntnd
            );
        }
        lvn_only_1_istep_2_call_id++;
        __program_velocity_no_nproma_if_prop_lvn_only_1_istep_2(
            state_lvn_only_1_istep_2,
            __CG_global_data__m_nflatlev,
            __CG_global_data__m_nrdmax,
            __CG_p_diag__m_ddt_vn_apc_pc,
            __CG_p_diag__m_vn_ie,
            __CG_p_diag__m_vt,
            __CG_p_diag__m_w_concorr_c,
            __CG_p_int__m_c_lin_e,
            __CG_p_int__m_e_bln_c_s,
            __CG_p_int__m_geofac_grdiv,
            __CG_p_int__m_geofac_rot,
            __CG_p_metrics__m_coeff_gradekin,
            __CG_p_metrics__m_ddqz_z_full_e,
            __CG_p_metrics__m_ddqz_z_half,
            __CG_p_patch__CG_cells__m_edge_blk,
            __CG_p_patch__CG_cells__m_edge_idx,
            __CG_p_patch__CG_cells__m_end_block,
            __CG_p_patch__CG_cells__m_end_index,
            __CG_p_patch__CG_cells__m_start_block,
            __CG_p_patch__CG_cells__m_start_index,
            __CG_p_patch__CG_edges__m_area_edge,
            __CG_p_patch__CG_edges__m_cell_blk,
            __CG_p_patch__CG_edges__m_cell_idx,
            __CG_p_patch__CG_edges__m_end_block,
            __CG_p_patch__CG_edges__m_end_index,
            __CG_p_patch__CG_edges__m_f_e,
            __CG_p_patch__CG_edges__m_inv_primal_edge_length,
            __CG_p_patch__CG_edges__m_quad_blk,
            __CG_p_patch__CG_edges__m_quad_idx,
            __CG_p_patch__CG_edges__m_start_block,
            __CG_p_patch__CG_edges__m_start_index,
            __CG_p_patch__CG_edges__m_tangent_orientation,
            __CG_p_patch__CG_edges__m_vertex_blk,
            __CG_p_patch__CG_edges__m_vertex_idx,
            __CG_p_patch__CG_verts__m_edge_blk,
            __CG_p_patch__CG_verts__m_edge_idx,
            __CG_p_patch__CG_verts__m_end_block,
            __CG_p_patch__CG_verts__m_end_index,
            __CG_p_patch__CG_verts__m_start_block,
            __CG_p_patch__CG_verts__m_start_index,
            __CG_p_prog__m_vn,
            __CG_p_prog__m_w,
            global_data,
            p_diag,
            p_int,
            p_metrics,
            p_patch,
            p_prog,
            z_kin_hor_e,
            z_vt_ie,
            z_w_concorr_me,
            __CG_global_data__m_nproma,
            __CG_p_diag__m_max_vcfl_dyn,
            __f2dace_A_z_kin_hor_e_d_0_s,
            __f2dace_A_z_kin_hor_e_d_1_s,
            __f2dace_OA_z_kin_hor_e_d_0_s,
            __f2dace_OA_z_kin_hor_e_d_1_s,
            __f2dace_OA_z_kin_hor_e_d_2_s,
            dt_linintp_ubc,
            dtime,
            istep,
            ldeepatmo,
            lvn_only,
            ntnd
        );
    } else if (lvn_only == 0 && istep == 1) {
        if (lvn_only_0_istep_1_call_id == 0) {
            state_lvn_only_0_istep_1 = __dace_init_velocity_no_nproma_if_prop_lvn_only_0_istep_1(
            __CG_global_data__m_nflatlev,
            __CG_global_data__m_nrdmax,
            __CG_p_diag__m_ddt_vn_apc_pc,
            __CG_p_diag__m_ddt_w_adv_pc,
            __CG_p_diag__m_vn_ie,
            __CG_p_diag__m_vt,
            __CG_p_diag__m_w_concorr_c,
            __CG_p_int__m_c_lin_e,
            __CG_p_int__m_cells_aw_verts,
            __CG_p_int__m_e_bln_c_s,
            __CG_p_int__m_geofac_grdiv,
            __CG_p_int__m_geofac_n2s,
            __CG_p_int__m_geofac_rot,
            __CG_p_int__m_rbf_vec_coeff_e,
            __CG_p_metrics__m_coeff1_dwdz,
            __CG_p_metrics__m_coeff2_dwdz,
            __CG_p_metrics__m_coeff_gradekin,
            __CG_p_metrics__m_ddqz_z_full_e,
            __CG_p_metrics__m_ddqz_z_half,
            __CG_p_metrics__m_ddxn_z_full,
            __CG_p_metrics__m_ddxt_z_full,
            __CG_p_metrics__m_wgtfac_c,
            __CG_p_metrics__m_wgtfac_e,
            __CG_p_metrics__m_wgtfacq_e,
            __CG_p_patch__CG_cells__CG_decomp_info__m_owner_mask,
            __CG_p_patch__CG_cells__m_area,
            __CG_p_patch__CG_cells__m_edge_blk,
            __CG_p_patch__CG_cells__m_edge_idx,
            __CG_p_patch__CG_cells__m_end_block,
            __CG_p_patch__CG_cells__m_end_index,
            __CG_p_patch__CG_cells__m_neighbor_blk,
            __CG_p_patch__CG_cells__m_neighbor_idx,
            __CG_p_patch__CG_cells__m_start_block,
            __CG_p_patch__CG_cells__m_start_index,
            __CG_p_patch__CG_edges__m_area_edge,
            __CG_p_patch__CG_edges__m_cell_blk,
            __CG_p_patch__CG_edges__m_cell_idx,
            __CG_p_patch__CG_edges__m_end_block,
            __CG_p_patch__CG_edges__m_end_index,
            __CG_p_patch__CG_edges__m_f_e,
            __CG_p_patch__CG_edges__m_inv_dual_edge_length,
            __CG_p_patch__CG_edges__m_inv_primal_edge_length,
            __CG_p_patch__CG_edges__m_quad_blk,
            __CG_p_patch__CG_edges__m_quad_idx,
            __CG_p_patch__CG_edges__m_start_block,
            __CG_p_patch__CG_edges__m_start_index,
            __CG_p_patch__CG_edges__m_tangent_orientation,
            __CG_p_patch__CG_edges__m_vertex_blk,
            __CG_p_patch__CG_edges__m_vertex_idx,
            __CG_p_patch__CG_verts__m_cell_blk,
            __CG_p_patch__CG_verts__m_cell_idx,
            __CG_p_patch__CG_verts__m_edge_blk,
            __CG_p_patch__CG_verts__m_edge_idx,
            __CG_p_patch__CG_verts__m_end_block,
            __CG_p_patch__CG_verts__m_end_index,
            __CG_p_patch__CG_verts__m_start_block,
            __CG_p_patch__CG_verts__m_start_index,
            __CG_p_prog__m_vn,
            __CG_p_prog__m_w,
            global_data,
            p_diag,
            p_int,
            p_metrics,
            p_patch,
            p_prog,
            z_kin_hor_e,
            z_vt_ie,
            z_w_concorr_me,
            __CG_global_data__m_nproma,
            __CG_p_diag__m_max_vcfl_dyn,
            __f2dace_A_z_kin_hor_e_d_0_s,
            __f2dace_A_z_kin_hor_e_d_1_s,
            __f2dace_A_z_vt_ie_d_0_s,
            __f2dace_A_z_vt_ie_d_1_s,
            __f2dace_A_z_w_concorr_me_d_0_s,
            __f2dace_A_z_w_concorr_me_d_1_s,
            __f2dace_OA_z_kin_hor_e_d_0_s,
            __f2dace_OA_z_kin_hor_e_d_1_s,
            __f2dace_OA_z_kin_hor_e_d_2_s,
            __f2dace_OA_z_vt_ie_d_0_s,
            __f2dace_OA_z_vt_ie_d_1_s,
            __f2dace_OA_z_vt_ie_d_2_s,
            __f2dace_OA_z_w_concorr_me_d_0_s,
            __f2dace_OA_z_w_concorr_me_d_1_s,
            __f2dace_OA_z_w_concorr_me_d_2_s,
            dt_linintp_ubc,
            dtime,
            istep,
            ldeepatmo,
            lvn_only,
            ntnd
            );
        }
        lvn_only_0_istep_1_call_id++;
        __program_velocity_no_nproma_if_prop_lvn_only_0_istep_1(
            state_lvn_only_0_istep_1,
            __CG_global_data__m_nflatlev,
            __CG_global_data__m_nrdmax,
            __CG_p_diag__m_ddt_vn_apc_pc,
            __CG_p_diag__m_ddt_w_adv_pc,
            __CG_p_diag__m_vn_ie,
            __CG_p_diag__m_vt,
            __CG_p_diag__m_w_concorr_c,
            __CG_p_int__m_c_lin_e,
            __CG_p_int__m_cells_aw_verts,
            __CG_p_int__m_e_bln_c_s,
            __CG_p_int__m_geofac_grdiv,
            __CG_p_int__m_geofac_n2s,
            __CG_p_int__m_geofac_rot,
            __CG_p_int__m_rbf_vec_coeff_e,
            __CG_p_metrics__m_coeff1_dwdz,
            __CG_p_metrics__m_coeff2_dwdz,
            __CG_p_metrics__m_coeff_gradekin,
            __CG_p_metrics__m_ddqz_z_full_e,
            __CG_p_metrics__m_ddqz_z_half,
            __CG_p_metrics__m_ddxn_z_full,
            __CG_p_metrics__m_ddxt_z_full,
            __CG_p_metrics__m_wgtfac_c,
            __CG_p_metrics__m_wgtfac_e,
            __CG_p_metrics__m_wgtfacq_e,
            __CG_p_patch__CG_cells__CG_decomp_info__m_owner_mask,
            __CG_p_patch__CG_cells__m_area,
            __CG_p_patch__CG_cells__m_edge_blk,
            __CG_p_patch__CG_cells__m_edge_idx,
            __CG_p_patch__CG_cells__m_end_block,
            __CG_p_patch__CG_cells__m_end_index,
            __CG_p_patch__CG_cells__m_neighbor_blk,
            __CG_p_patch__CG_cells__m_neighbor_idx,
            __CG_p_patch__CG_cells__m_start_block,
            __CG_p_patch__CG_cells__m_start_index,
            __CG_p_patch__CG_edges__m_area_edge,
            __CG_p_patch__CG_edges__m_cell_blk,
            __CG_p_patch__CG_edges__m_cell_idx,
            __CG_p_patch__CG_edges__m_end_block,
            __CG_p_patch__CG_edges__m_end_index,
            __CG_p_patch__CG_edges__m_f_e,
            __CG_p_patch__CG_edges__m_inv_dual_edge_length,
            __CG_p_patch__CG_edges__m_inv_primal_edge_length,
            __CG_p_patch__CG_edges__m_quad_blk,
            __CG_p_patch__CG_edges__m_quad_idx,
            __CG_p_patch__CG_edges__m_start_block,
            __CG_p_patch__CG_edges__m_start_index,
            __CG_p_patch__CG_edges__m_tangent_orientation,
            __CG_p_patch__CG_edges__m_vertex_blk,
            __CG_p_patch__CG_edges__m_vertex_idx,
            __CG_p_patch__CG_verts__m_cell_blk,
            __CG_p_patch__CG_verts__m_cell_idx,
            __CG_p_patch__CG_verts__m_edge_blk,
            __CG_p_patch__CG_verts__m_edge_idx,
            __CG_p_patch__CG_verts__m_end_block,
            __CG_p_patch__CG_verts__m_end_index,
            __CG_p_patch__CG_verts__m_start_block,
            __CG_p_patch__CG_verts__m_start_index,
            __CG_p_prog__m_vn,
            __CG_p_prog__m_w,
            global_data,
            p_diag,
            p_int,
            p_metrics,
            p_patch,
            p_prog,
            z_kin_hor_e,
            z_vt_ie,
            z_w_concorr_me,
            __CG_global_data__m_nproma,
            __CG_p_diag__m_max_vcfl_dyn,
            __f2dace_A_z_kin_hor_e_d_0_s,
            __f2dace_A_z_kin_hor_e_d_1_s,
            __f2dace_A_z_vt_ie_d_0_s,
            __f2dace_A_z_vt_ie_d_1_s,
            __f2dace_A_z_w_concorr_me_d_0_s,
            __f2dace_A_z_w_concorr_me_d_1_s,
            __f2dace_OA_z_kin_hor_e_d_0_s,
            __f2dace_OA_z_kin_hor_e_d_1_s,
            __f2dace_OA_z_kin_hor_e_d_2_s,
            __f2dace_OA_z_vt_ie_d_0_s,
            __f2dace_OA_z_vt_ie_d_1_s,
            __f2dace_OA_z_vt_ie_d_2_s,
            __f2dace_OA_z_w_concorr_me_d_0_s,
            __f2dace_OA_z_w_concorr_me_d_1_s,
            __f2dace_OA_z_w_concorr_me_d_2_s,
            dt_linintp_ubc,
            dtime,
            istep,
            ldeepatmo,
            lvn_only,
            ntnd
        );
    } else if (lvn_only == 0 && istep == 2) {
        if (lvn_only_0_istep_2_call_id == 0) {
            state_lvn_only_0_istep_2 = __dace_init_velocity_no_nproma_if_prop_lvn_only_0_istep_2(
            __CG_global_data__m_nflatlev,
            __CG_global_data__m_nrdmax,
            __CG_p_diag__m_ddt_vn_apc_pc,
            __CG_p_diag__m_ddt_w_adv_pc,
            __CG_p_diag__m_vn_ie,
            __CG_p_diag__m_vt,
            __CG_p_diag__m_w_concorr_c,
            __CG_p_int__m_c_lin_e,
            __CG_p_int__m_cells_aw_verts,
            __CG_p_int__m_e_bln_c_s,
            __CG_p_int__m_geofac_grdiv,
            __CG_p_int__m_geofac_n2s,
            __CG_p_int__m_geofac_rot,
            __CG_p_metrics__m_coeff1_dwdz,
            __CG_p_metrics__m_coeff2_dwdz,
            __CG_p_metrics__m_coeff_gradekin,
            __CG_p_metrics__m_ddqz_z_full_e,
            __CG_p_metrics__m_ddqz_z_half,
            __CG_p_patch__CG_cells__CG_decomp_info__m_owner_mask,
            __CG_p_patch__CG_cells__m_area,
            __CG_p_patch__CG_cells__m_edge_blk,
            __CG_p_patch__CG_cells__m_edge_idx,
            __CG_p_patch__CG_cells__m_end_block,
            __CG_p_patch__CG_cells__m_end_index,
            __CG_p_patch__CG_cells__m_neighbor_blk,
            __CG_p_patch__CG_cells__m_neighbor_idx,
            __CG_p_patch__CG_cells__m_start_block,
            __CG_p_patch__CG_cells__m_start_index,
            __CG_p_patch__CG_edges__m_area_edge,
            __CG_p_patch__CG_edges__m_cell_blk,
            __CG_p_patch__CG_edges__m_cell_idx,
            __CG_p_patch__CG_edges__m_end_block,
            __CG_p_patch__CG_edges__m_end_index,
            __CG_p_patch__CG_edges__m_f_e,
            __CG_p_patch__CG_edges__m_inv_dual_edge_length,
            __CG_p_patch__CG_edges__m_inv_primal_edge_length,
            __CG_p_patch__CG_edges__m_quad_blk,
            __CG_p_patch__CG_edges__m_quad_idx,
            __CG_p_patch__CG_edges__m_start_block,
            __CG_p_patch__CG_edges__m_start_index,
            __CG_p_patch__CG_edges__m_tangent_orientation,
            __CG_p_patch__CG_edges__m_vertex_blk,
            __CG_p_patch__CG_edges__m_vertex_idx,
            __CG_p_patch__CG_verts__m_cell_blk,
            __CG_p_patch__CG_verts__m_cell_idx,
            __CG_p_patch__CG_verts__m_edge_blk,
            __CG_p_patch__CG_verts__m_edge_idx,
            __CG_p_patch__CG_verts__m_end_block,
            __CG_p_patch__CG_verts__m_end_index,
            __CG_p_patch__CG_verts__m_start_block,
            __CG_p_patch__CG_verts__m_start_index,
            __CG_p_prog__m_vn,
            __CG_p_prog__m_w,
            global_data,
            p_diag,
            p_int,
            p_metrics,
            p_patch,
            p_prog,
            z_kin_hor_e,
            z_vt_ie,
            z_w_concorr_me,
            __CG_global_data__m_nproma,
            __CG_p_diag__m_max_vcfl_dyn,
            __f2dace_A_z_kin_hor_e_d_0_s,
            __f2dace_A_z_kin_hor_e_d_1_s,
            __f2dace_A_z_vt_ie_d_0_s,
            __f2dace_A_z_vt_ie_d_1_s,
            __f2dace_OA_z_kin_hor_e_d_0_s,
            __f2dace_OA_z_kin_hor_e_d_1_s,
            __f2dace_OA_z_kin_hor_e_d_2_s,
            __f2dace_OA_z_vt_ie_d_0_s,
            __f2dace_OA_z_vt_ie_d_1_s,
            __f2dace_OA_z_vt_ie_d_2_s,
            dt_linintp_ubc,
            dtime,
            istep,
            ldeepatmo,
            lvn_only,
            ntnd
            );
        }
        lvn_only_0_istep_2_call_id++;
        __program_velocity_no_nproma_if_prop_lvn_only_0_istep_2(
            state_lvn_only_0_istep_2,
            __CG_global_data__m_nflatlev,
            __CG_global_data__m_nrdmax,
            __CG_p_diag__m_ddt_vn_apc_pc,
            __CG_p_diag__m_ddt_w_adv_pc,
            __CG_p_diag__m_vn_ie,
            __CG_p_diag__m_vt,
            __CG_p_diag__m_w_concorr_c,
            __CG_p_int__m_c_lin_e,
            __CG_p_int__m_cells_aw_verts,
            __CG_p_int__m_e_bln_c_s,
            __CG_p_int__m_geofac_grdiv,
            __CG_p_int__m_geofac_n2s,
            __CG_p_int__m_geofac_rot,
            __CG_p_metrics__m_coeff1_dwdz,
            __CG_p_metrics__m_coeff2_dwdz,
            __CG_p_metrics__m_coeff_gradekin,
            __CG_p_metrics__m_ddqz_z_full_e,
            __CG_p_metrics__m_ddqz_z_half,
            __CG_p_patch__CG_cells__CG_decomp_info__m_owner_mask,
            __CG_p_patch__CG_cells__m_area,
            __CG_p_patch__CG_cells__m_edge_blk,
            __CG_p_patch__CG_cells__m_edge_idx,
            __CG_p_patch__CG_cells__m_end_block,
            __CG_p_patch__CG_cells__m_end_index,
            __CG_p_patch__CG_cells__m_neighbor_blk,
            __CG_p_patch__CG_cells__m_neighbor_idx,
            __CG_p_patch__CG_cells__m_start_block,
            __CG_p_patch__CG_cells__m_start_index,
            __CG_p_patch__CG_edges__m_area_edge,
            __CG_p_patch__CG_edges__m_cell_blk,
            __CG_p_patch__CG_edges__m_cell_idx,
            __CG_p_patch__CG_edges__m_end_block,
            __CG_p_patch__CG_edges__m_end_index,
            __CG_p_patch__CG_edges__m_f_e,
            __CG_p_patch__CG_edges__m_inv_dual_edge_length,
            __CG_p_patch__CG_edges__m_inv_primal_edge_length,
            __CG_p_patch__CG_edges__m_quad_blk,
            __CG_p_patch__CG_edges__m_quad_idx,
            __CG_p_patch__CG_edges__m_start_block,
            __CG_p_patch__CG_edges__m_start_index,
            __CG_p_patch__CG_edges__m_tangent_orientation,
            __CG_p_patch__CG_edges__m_vertex_blk,
            __CG_p_patch__CG_edges__m_vertex_idx,
            __CG_p_patch__CG_verts__m_cell_blk,
            __CG_p_patch__CG_verts__m_cell_idx,
            __CG_p_patch__CG_verts__m_edge_blk,
            __CG_p_patch__CG_verts__m_edge_idx,
            __CG_p_patch__CG_verts__m_end_block,
            __CG_p_patch__CG_verts__m_end_index,
            __CG_p_patch__CG_verts__m_start_block,
            __CG_p_patch__CG_verts__m_start_index,
            __CG_p_prog__m_vn,
            __CG_p_prog__m_w,
            global_data,
            p_diag,
            p_int,
            p_metrics,
            p_patch,
            p_prog,
            z_kin_hor_e,
            z_vt_ie,
            z_w_concorr_me,
            __CG_global_data__m_nproma,
            __CG_p_diag__m_max_vcfl_dyn,
            __f2dace_A_z_kin_hor_e_d_0_s,
            __f2dace_A_z_kin_hor_e_d_1_s,
            __f2dace_A_z_vt_ie_d_0_s,
            __f2dace_A_z_vt_ie_d_1_s,
            __f2dace_OA_z_kin_hor_e_d_0_s,
            __f2dace_OA_z_kin_hor_e_d_1_s,
            __f2dace_OA_z_kin_hor_e_d_2_s,
            __f2dace_OA_z_vt_ie_d_0_s,
            __f2dace_OA_z_vt_ie_d_1_s,
            __f2dace_OA_z_vt_ie_d_2_s,
            dt_linintp_ubc,
            dtime,
            istep,
            ldeepatmo,
            lvn_only,
            ntnd
        );
    }
}

static void exit_velocity_tendencies() {
    if (state_lvn_only_1_istep_1 != nullptr) {
        __dace_exit_velocity_no_nproma_if_prop_lvn_only_1_istep_1(state_lvn_only_1_istep_1);
        state_lvn_only_1_istep_1 = nullptr;
    }
    if (state_lvn_only_1_istep_2 != nullptr) {
        __dace_exit_velocity_no_nproma_if_prop_lvn_only_1_istep_2(state_lvn_only_1_istep_2);
        state_lvn_only_1_istep_2 = nullptr;
    }
    if (state_lvn_only_0_istep_1 != nullptr) {
        __dace_exit_velocity_no_nproma_if_prop_lvn_only_0_istep_1(state_lvn_only_0_istep_1);
        state_lvn_only_0_istep_1 = nullptr;
    }
    if (state_lvn_only_0_istep_2 != nullptr) {
        __dace_exit_velocity_no_nproma_if_prop_lvn_only_0_istep_2(state_lvn_only_0_istep_2);
        state_lvn_only_0_istep_2 = nullptr;
    }
}

#endif // GPU
#endif // __VELOCITY_SHIM_H__
